// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal         ErrorCode = "internal"
	ErrorCodeNotFound         ErrorCode = "not-found"
	ErrorCodePermissionDenied ErrorCode = "permission-denied"
	ErrorCodeRateLimited      ErrorCode = "rate-limited"
	ErrorCodeUnauthenticated  ErrorCode = "unauthenticated"
	ErrorCodeValidationFailed ErrorCode = "validation-failed"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for SessionUserRole.
const (
	Operator SessionUserRole = "operator"
	Owner    SessionUserRole = "owner"
)

// Valid indicates whether the value is a known member of the SessionUserRole enum.
func (e SessionUserRole) Valid() bool {
	switch e {
	case Operator:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// ErrorCode Kode error generik yang dipakai setiap endpoint sebelum sampai ke aturan bisnisnya.
// Kode spesifik per aturan bisnis ada di `04-api-spec.md` §2 dan ditambahkan oleh item
// backlog yang memilikinya.
//
// Kodenya juga jadi segmen terakhir URI `Problem.type`, dan memakai **hyphen**, bukan
// underscore.
type ErrorCode string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Examples: budi@rentalbudi.id
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Me Bentuk yang sama dengan `Session` dikurangi tokennya. `GET /me` dipanggil saat reload
// halaman, ketika access token sudah ada di memori dan yang dibutuhkan cuma konteksnya.
type Me struct {
	// Owner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
	// pengalih (BR-004).
	//
	// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
	// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
	// Asia/Jakarta urusan render di frontend.
	Owner SessionOwner `json:"owner"`
	User  SessionUser  `json:"user"`
}

// Problem RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Problem struct {
	// Detail Examples: Aksi ini butuh izin bookings:write.
	Detail *string         `json:"detail,omitempty"`
	Errors *[]ProblemError `json:"errors,omitempty"`

	// Instance Examples: /api/v1/bookings/01926f3a-0000-7000-8000-000000000000
	Instance *string `json:"instance,omitempty"`

	// Status Examples: 403
	Status int `json:"status"`

	// Title Examples: Tidak punya izin
	Title string `json:"title"`

	// TraceId Examples: 4bf92f3577b34da6a3ce929d0e0e4736
	TraceId string `json:"trace_id"`

	// Type Examples: https://sewain.id/problems/permission-denied
	Type string `json:"type"`
}

// ProblemError Satu detail per-field di dalam `Problem`. Ia membawa apa pun yang dibutuhkan kegagalan
// spesifiknya, jadi properti tambahan diizinkan secara desain.
type ProblemError struct {
	Detail *string `json:"detail,omitempty"`

	// Field Examples: email
	Field                string                 `json:"field"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Session Dikembalikan login dan refresh. Membawa semua yang dibutuhkan klien untuk merender
// kerangka aplikasi tanpa request kedua.
//
// Refresh token **tidak** ada di sini — ia di cookie httpOnly, di luar jangkauan script
// mana pun di halaman itu.
type Session struct {
	// AccessToken JWT. Disimpan di memori saja, tidak pernah di localStorage.
	AccessToken string `json:"access_token"`

	// ExpiresIn Detik sampai access token kedaluwarsa.
	//
	// Examples: 900
	ExpiresIn int `json:"expires_in"`

	// Owner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
	// pengalih (BR-004).
	//
	// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
	// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
	// Asia/Jakarta urusan render di frontend.
	Owner SessionOwner `json:"owner"`
	User  SessionUser  `json:"user"`
}

// SessionOwner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
// pengalih (BR-004).
//
// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
// Asia/Jakarta urusan render di frontend.
type SessionOwner struct {
	Id openapi_types.UUID `json:"id"`

	// Name Examples: Rental Budi
	Name string `json:"name"`

	// Slug Label subdomain usaha ini — `rentalbudi` berarti `rentalbudi.sewain.id` (BR-025).
	//
	//
	// Examples: rentalbudi
	Slug string `json:"slug"`
}

// SessionUser defines model for SessionUser.
type SessionUser struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Permissions String `resource:action` yang diberikan peran itu. Klien **menyembunyikan** aksi
	// yang tidak ada di sini, bukan menonaktifkannya — tombol yang `403` mengiklankan
	// kemampuan yang tidak dimiliki penggunanya.
	Permissions []string `json:"permissions"`

	// Role Satu peran per orang, karena satu orang punya satu usaha (BR-003, BR-004).
	Role SessionUserRole `json:"role"`
}

// SessionUserRole Satu peran per orang, karena satu orang punya satu usaha (BR-003, BR-004).
type SessionUserRole string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type BadRequest = Problem

// Conflict RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Conflict = Problem

// Forbidden RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Forbidden = Problem

// NotFound RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type NotFound = Problem

// TooManyRequests RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type TooManyRequests = Problem

// Unauthorized RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type UnprocessableEntity = Problem

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// Getter for additional properties for ProblemError. Returns the specified
// element and whether it was found
func (a ProblemError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemError
func (a *ProblemError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a *ProblemError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a ProblemError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Tukar email dan password dengan access token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Cabut refresh token yang sedang dipakai
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh Rotasi refresh token dan terbitkan access token baru
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Tukar email dan password dengan access token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Cabut refresh token yang sedang dipakai
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotasi refresh token dan terbitkan access token baru
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RateLimitLimit     *int
	RateLimitRemaining *int
	RateLimitReset     *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    Session
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response Login422ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimitLimit != nil {
		w.Header().Set("RateLimit-Limit", fmt.Sprint(*response.Headers.RateLimitLimit))
	}
	if response.Headers.RateLimitRemaining != nil {
		w.Header().Set("RateLimit-Remaining", fmt.Sprint(*response.Headers.RateLimitRemaining))
	}
	if response.Headers.RateLimitReset != nil {
		w.Header().Set("RateLimit-Reset", fmt.Sprint(*response.Headers.RateLimitReset))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200ResponseHeaders struct {
	SetCookie *string
}

type Refresh200JSONResponse struct {
	Body    Session
	Headers Refresh200ResponseHeaders
}

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Refresh401ApplicationProblemPlusJSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Tukar email dan password dengan access token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Cabut refresh token yang sedang dipakai
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh Rotasi refresh token dan terbitkan access token baru
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
