// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeEmailTaken       ErrorCode = "email-taken"
	ErrorCodeInternal         ErrorCode = "internal"
	ErrorCodeNotFound         ErrorCode = "not-found"
	ErrorCodePermissionDenied ErrorCode = "permission-denied"
	ErrorCodeRateLimited      ErrorCode = "rate-limited"
	ErrorCodeSlugInvalid      ErrorCode = "slug-invalid"
	ErrorCodeSlugTaken        ErrorCode = "slug-taken"
	ErrorCodeUnauthenticated  ErrorCode = "unauthenticated"
	ErrorCodeValidationFailed ErrorCode = "validation-failed"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeEmailTaken:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeSlugInvalid:
		return true
	case ErrorCodeSlugTaken:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for InviteUserRequestRole.
const (
	InviteUserRequestRoleOperator InviteUserRequestRole = "operator"
	InviteUserRequestRoleOwner    InviteUserRequestRole = "owner"
)

// Valid indicates whether the value is a known member of the InviteUserRequestRole enum.
func (e InviteUserRequestRole) Valid() bool {
	switch e {
	case InviteUserRequestRoleOperator:
		return true
	case InviteUserRequestRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for SessionUserRole.
const (
	SessionUserRoleOperator SessionUserRole = "operator"
	SessionUserRoleOwner    SessionUserRole = "owner"
)

// Valid indicates whether the value is a known member of the SessionUserRole enum.
func (e SessionUserRole) Valid() bool {
	switch e {
	case SessionUserRoleOperator:
		return true
	case SessionUserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRequestRole.
const (
	UpdateUserRequestRoleOperator UpdateUserRequestRole = "operator"
	UpdateUserRequestRoleOwner    UpdateUserRequestRole = "owner"
)

// Valid indicates whether the value is a known member of the UpdateUserRequestRole enum.
func (e UpdateUserRequestRole) Valid() bool {
	switch e {
	case UpdateUserRequestRoleOperator:
		return true
	case UpdateUserRequestRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRequestStatus.
const (
	UpdateUserRequestStatusActive   UpdateUserRequestStatus = "active"
	UpdateUserRequestStatusDisabled UpdateUserRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateUserRequestStatus enum.
func (e UpdateUserRequestStatus) Valid() bool {
	switch e {
	case UpdateUserRequestStatusActive:
		return true
	case UpdateUserRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleOperator UserRole = "operator"
	UserRoleOwner    UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleOperator:
		return true
	case UserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
	UserStatusInvited  UserStatus = "invited"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDisabled:
		return true
	case UserStatusInvited:
		return true
	default:
		return false
	}
}

// ErrorCode Kode error generik yang dipakai setiap endpoint sebelum sampai ke aturan bisnisnya.
// Kode spesifik per aturan bisnis ada di `04-api-spec.md` §2 dan ditambahkan oleh item
// backlog yang memilikinya.
//
// Kodenya juga jadi segmen terakhir URI `Problem.type`, dan memakai **hyphen**, bukan
// underscore.
type ErrorCode string

// InviteUserRequest defines model for InviteUserRequest.
type InviteUserRequest struct {
	Email openapi_types.Email    `json:"email"`
	Name  string                 `json:"name"`
	Role  *InviteUserRequestRole `json:"role,omitempty"`
}

// InviteUserRequestRole defines model for InviteUserRequest.Role.
type InviteUserRequestRole string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Examples: budi@rentalbudi.id
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Me Bentuk yang sama dengan `Session` dikurangi tokennya. `GET /me` dipanggil saat reload
// halaman, ketika access token sudah ada di memori dan yang dibutuhkan cuma konteksnya.
type Me struct {
	// Owner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
	// pengalih (BR-004).
	//
	// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
	// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
	// Asia/Jakarta urusan render di frontend.
	Owner SessionOwner `json:"owner"`
	User  SessionUser  `json:"user"`
}

// Problem RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Problem struct {
	// Detail Examples: Aksi ini butuh izin bookings:write.
	Detail *string         `json:"detail,omitempty"`
	Errors *[]ProblemError `json:"errors,omitempty"`

	// Instance Examples: /api/v1/bookings/01926f3a-0000-7000-8000-000000000000
	Instance *string `json:"instance,omitempty"`

	// Status Examples: 403
	Status int `json:"status"`

	// Title Examples: Tidak punya izin
	Title string `json:"title"`

	// TraceId Examples: 4bf92f3577b34da6a3ce929d0e0e4736
	TraceId string `json:"trace_id"`

	// Type Examples: https://sewain.id/problems/permission-denied
	Type string `json:"type"`
}

// ProblemError Satu detail per-field di dalam `Problem`. Ia membawa apa pun yang dibutuhkan kegagalan
// spesifiknya, jadi properti tambahan diizinkan secara desain.
type ProblemError struct {
	Detail *string `json:"detail,omitempty"`

	// Field Examples: email
	Field                string                 `json:"field"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Session Dikembalikan login dan refresh. Membawa semua yang dibutuhkan klien untuk merender
// kerangka aplikasi tanpa request kedua.
//
// Refresh token **tidak** ada di sini — ia di cookie httpOnly, di luar jangkauan script
// mana pun di halaman itu.
type Session struct {
	// AccessToken JWT. Disimpan di memori saja, tidak pernah di localStorage.
	AccessToken string `json:"access_token"`

	// ExpiresIn Detik sampai access token kedaluwarsa.
	//
	// Examples: 900
	ExpiresIn int `json:"expires_in"`

	// Owner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
	// pengalih (BR-004).
	//
	// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
	// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
	// Asia/Jakarta urusan render di frontend.
	Owner SessionOwner `json:"owner"`
	User  SessionUser  `json:"user"`
}

// SessionOwner Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
// pengalih (BR-004).
//
// Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
// (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
// Asia/Jakarta urusan render di frontend.
type SessionOwner struct {
	Id openapi_types.UUID `json:"id"`

	// Name Examples: Rental Budi
	Name string `json:"name"`

	// Slug Label subdomain usaha ini — `rentalbudi` berarti `rentalbudi.sewain.id` (BR-025).
	//
	// **`null` adalah keadaan awal setiap usaha**, bukan kasus pinggir: slug tidak
	// ditanyakan saat daftar (BR-005) dan diisi belakangan dari `PATCH /settings`.
	// Pemilik tanpa slug tidak punya host sama sekali — katalog publik maupun portal
	// penyewa ikut tidak ada. Karena itu ia tidak `required`: usaha yang baru saja
	// terbit lewat `POST /auth/register` tidak bisa memenuhinya.
	//
	//
	// Examples: rentalbudi
	Slug *string `json:"slug,omitempty"`
}

// SessionUser defines model for SessionUser.
type SessionUser struct {
	// EmailVerifiedAt `null` selama email belum terverifikasi. Frontend merender dinding verifikasi
	// dari field ini, bukan dari menebak lewat `403 email-not-verified` — gerbang itu
	// bisa muncul di endpoint mana pun, jadi menebaknya berarti menebak di tiap layar
	// (BR-006).
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Id              openapi_types.UUID `json:"id"`
	Name            string             `json:"name"`

	// Permissions String `resource:action` yang diberikan peran itu. Klien **menyembunyikan** aksi
	// yang tidak ada di sini, bukan menonaktifkannya — tombol yang `403` mengiklankan
	// kemampuan yang tidak dimiliki penggunanya.
	Permissions []string `json:"permissions"`

	// Role Satu peran per orang, karena satu orang punya satu usaha (BR-003, BR-004).
	Role SessionUserRole `json:"role"`
}

// SessionUserRole Satu peran per orang, karena satu orang punya satu usaha (BR-003, BR-004).
type SessionUserRole string

// Settings Knob pemilik, semuanya. Tiap satu ada karena sebuah aturan bisnis melarang
// meng-hardcode-nya, dan `PATCH /settings` satu-satunya tempat mereka disetel.
type Settings struct {
	// BookingCodePrefix Awalan kode booking, `SWN-0001`. Mengubahnya **tidak** menyentuh kode yang sudah
	// terbit dan **tidak** me-reset pencacahnya (BR-024).
	//
	//
	// Examples: RBD
	BookingCodePrefix string `json:"booking_code_prefix"`

	// DraftExpiryHours Umur draft dari halaman publik sebelum dibatalkan otomatis (BR-027).
	DraftExpiryHours int `json:"draft_expiry_hours"`

	// NoShowToleranceHours Tenggang sesudah `start_at` sebelum booking ditandai `no_show`. **`0` diterima**,
	// dan itu bedanya dengan `payment_due_hours` — pemilik yang mau membebaskan unitnya
	// di hari yang sama memang menyetelnya nol (BR-057).
	NoShowToleranceHours int `json:"no_show_tolerance_hours"`

	// NotifyOverdueReminder Pengingat saat kondisi telat terpenuhi (BR-070).
	NotifyOverdueReminder bool `json:"notify_overdue_reminder"`

	// NotifyPickupReminder Pengingat H-1 ambil (BR-070).
	NotifyPickupReminder bool `json:"notify_pickup_reminder"`

	// NotifyReturnReminder Pengingat H-1 balik (BR-070).
	NotifyReturnReminder bool `json:"notify_return_reminder"`

	// PaymentDueHours Tenggat bayar sejak invoice terbit. **`0` ditolak database** — tenggat nol berarti
	// invoice yang lewat tempo pada detik ia terbit (BR-057).
	PaymentDueHours int `json:"payment_due_hours"`

	// RequirePaymentBeforePickup Kalau menyala, pengambilan ditolak selama invoicenya belum lunas (BR-038).
	RequirePaymentBeforePickup bool `json:"require_payment_before_pickup"`

	// Slug Sama dengan `SessionOwner.slug`: `null` adalah keadaan awal, dan di sinilah ia
	// diisi — bukan saat daftar (BR-005, BR-025).
	//
	// **Belum ada yang membacanya sampai M5** (`S1-051`, `S1-060`). Ia tersimpan dan
	// tervalidasi di sini, tapi halaman publiknya baru hidup 12 minggu kemudian, dan
	// layar pengaturan wajib jujur soal itu.
	//
	//
	// Examples: rentalbudi
	Slug *string `json:"slug"`
}

// SettingsUpdate Semua field opsional. Key yang absen dibiarkan apa adanya; `null` eksplisit adalah
// `422` — menghilangkan field dan mengirim `null` bukan hal yang sama.
type SettingsUpdate struct {
	BookingCodePrefix          *string `json:"booking_code_prefix,omitempty"`
	DraftExpiryHours           *int    `json:"draft_expiry_hours,omitempty"`
	NoShowToleranceHours       *int    `json:"no_show_tolerance_hours,omitempty"`
	NotifyOverdueReminder      *bool   `json:"notify_overdue_reminder,omitempty"`
	NotifyPickupReminder       *bool   `json:"notify_pickup_reminder,omitempty"`
	NotifyReturnReminder       *bool   `json:"notify_return_reminder,omitempty"`
	PaymentDueHours            *int    `json:"payment_due_hours,omitempty"`
	RequirePaymentBeforePickup *bool   `json:"require_payment_before_pickup,omitempty"`

	// Slug Examples: rentalbudi
	Slug *string `json:"slug,omitempty"`
}

// UpdateUserRequest Minimal satu field. `email` dan `owner_id` sengaja tidak ada di sini.
type UpdateUserRequest struct {
	Role *UpdateUserRequestRole `json:"role,omitempty"`

	// Status `invited` tidak ada di sini — ia dikelola server dan cuma berlaku sebelum
	// undangannya diterima.
	Status *UpdateUserRequestStatus `json:"status,omitempty"`
}

// UpdateUserRequestRole defines model for UpdateUserRequest.Role.
type UpdateUserRequestRole string

// UpdateUserRequestStatus `invited` tidak ada di sini — ia dikelola server dan cuma berlaku sebelum
// undangannya diterima.
type UpdateUserRequestStatus string

// User Akun di usaha ini. Tidak pernah memuat `password_hash` maupun `owner_id` — yang
// pertama rahasia, yang kedua sudah tersirat dari usaha pemanggilnya.
type User struct {
	// Email Unik di seluruh sistem, bukan per usaha (BR-004).
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	LastLoginAt *time.Time          `json:"last_login_at,omitempty"`
	Name        string              `json:"name"`
	Role        UserRole            `json:"role"`

	// Status `invited` sampai undangannya diterima, `disabled` sesudah dinonaktifkan. Nol
	// endpoint di API ini yang menghapus baris `users`.
	Status UserStatus `json:"status"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserStatus `invited` sampai undangannya diterima, `disabled` sesudah dinonaktifkan. Nol
// endpoint di API ini yang menghapus baris `users`.
type UserStatus string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type BadRequest = Problem

// Conflict RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Conflict = Problem

// Forbidden RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Forbidden = Problem

// NotFound RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type NotFound = Problem

// TooManyRequests RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type TooManyRequests = Problem

// Unauthorized RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
//
// `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
// menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
// `type` (BR-092).
type UnprocessableEntity = Problem

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsUpdate

// InviteUserJSONRequestBody defines body for InviteUser for application/json ContentType.
type InviteUserJSONRequestBody = InviteUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// Getter for additional properties for ProblemError. Returns the specified
// element and whether it was found
func (a ProblemError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemError
func (a *ProblemError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a *ProblemError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a ProblemError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Tukar email dan password dengan access token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Cabut refresh token yang sedang dipakai
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh Rotasi refresh token dan terbitkan access token baru
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// GetSettings Baca knob pemilik
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// UpdateSettings Ubah knob pemilik
	// (PATCH /settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// ListUsers Akun di usaha ini
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// InviteUser Undang akun ke usaha ini
	// (POST /users)
	InviteUser(w http.ResponseWriter, r *http.Request)
	// DisableUser Nonaktifkan akun
	// (DELETE /users/{id})
	DisableUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateUser Ubah peran atau status akun
	// (PATCH /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Tukar email dan password dengan access token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Cabut refresh token yang sedang dipakai
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotasi refresh token dan terbitkan access token baru
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSettings Baca knob pemilik
// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateSettings Ubah knob pemilik
// (PATCH /settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUsers Akun di usaha ini
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// InviteUser Undang akun ke usaha ini
// (POST /users)
func (_ Unimplemented) InviteUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DisableUser Nonaktifkan akun
// (DELETE /users/{id})
func (_ Unimplemented) DisableUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateUser Ubah peran atau status akun
// (PATCH /users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InviteUser operation middleware
func (siw *ServerInterfaceWrapper) InviteUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InviteUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableUser operation middleware
func (siw *ServerInterfaceWrapper) DisableUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.InviteUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DisableUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{id}", wrapper.UpdateUser)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RateLimitLimit     *int
	RateLimitRemaining *int
	RateLimitReset     *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    Session
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response Login422ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimitLimit != nil {
		w.Header().Set("RateLimit-Limit", fmt.Sprint(*response.Headers.RateLimitLimit))
	}
	if response.Headers.RateLimitRemaining != nil {
		w.Header().Set("RateLimit-Remaining", fmt.Sprint(*response.Headers.RateLimitRemaining))
	}
	if response.Headers.RateLimitReset != nil {
		w.Header().Set("RateLimit-Reset", fmt.Sprint(*response.Headers.RateLimitReset))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200ResponseHeaders struct {
	SetCookie *string
}

type Refresh200JSONResponse struct {
	Body    Session
	Headers Refresh200ResponseHeaders
}

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Refresh401ApplicationProblemPlusJSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettings401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSettings401ApplicationProblemPlusJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettings403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetSettings403ApplicationProblemPlusJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettingsRequestObject struct {
	Body *UpdateSettingsJSONRequestBody
}

type UpdateSettingsResponseObject interface {
	VisitUpdateSettingsResponse(w http.ResponseWriter) error
}

type UpdateSettings200JSONResponse Settings

func (response UpdateSettings200JSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettings401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateSettings401ApplicationProblemPlusJSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettings403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateSettings403ApplicationProblemPlusJSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettings422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response UpdateSettings422ApplicationProblemPlusJSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse []User

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsers401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListUsers401ApplicationProblemPlusJSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsers403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListUsers403ApplicationProblemPlusJSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type InviteUserRequestObject struct {
	Body *InviteUserJSONRequestBody
}

type InviteUserResponseObject interface {
	VisitInviteUserResponse(w http.ResponseWriter) error
}

type InviteUser201JSONResponse User

func (response InviteUser201JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type InviteUser401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response InviteUser401ApplicationProblemPlusJSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type InviteUser403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response InviteUser403ApplicationProblemPlusJSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type InviteUser422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response InviteUser422ApplicationProblemPlusJSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DisableUserRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DisableUserResponseObject interface {
	VisitDisableUserResponse(w http.ResponseWriter) error
}

type DisableUser204Response struct {
}

func (response DisableUser204Response) VisitDisableUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DisableUser401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DisableUser401ApplicationProblemPlusJSONResponse) VisitDisableUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DisableUser403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DisableUser403ApplicationProblemPlusJSONResponse) VisitDisableUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DisableUser404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DisableUser404ApplicationProblemPlusJSONResponse) VisitDisableUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateUserJSONRequestBody
}

type UpdateUserResponseObject interface {
	VisitUpdateUserResponse(w http.ResponseWriter) error
}

type UpdateUser200JSONResponse User

func (response UpdateUser200JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateUser401ApplicationProblemPlusJSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateUser403ApplicationProblemPlusJSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateUser404ApplicationProblemPlusJSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response UpdateUser422ApplicationProblemPlusJSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Tukar email dan password dengan access token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Cabut refresh token yang sedang dipakai
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh Rotasi refresh token dan terbitkan access token baru
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// GetMe Usaha, peran, dan izin pengguna yang sedang masuk
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetSettings Baca knob pemilik
	// (GET /settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// UpdateSettings Ubah knob pemilik
	// (PATCH /settings)
	UpdateSettings(ctx context.Context, request UpdateSettingsRequestObject) (UpdateSettingsResponseObject, error)
	// ListUsers Akun di usaha ini
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// InviteUser Undang akun ke usaha ini
	// (POST /users)
	InviteUser(ctx context.Context, request InviteUserRequestObject) (InviteUserResponseObject, error)
	// DisableUser Nonaktifkan akun
	// (DELETE /users/{id})
	DisableUser(ctx context.Context, request DisableUserRequestObject) (DisableUserResponseObject, error)
	// UpdateUser Ubah peran atau status akun
	// (PATCH /users/{id})
	UpdateUser(ctx context.Context, request UpdateUserRequestObject) (UpdateUserResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(w http.ResponseWriter, r *http.Request) {
	var request GetSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx, request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		if err := validResponse.VisitGetSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSettings operation middleware
func (sh *strictHandler) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	var request UpdateSettingsRequestObject

	var body UpdateSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSettings(ctx, request.(UpdateSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSettingsResponseObject); ok {
		if err := validResponse.VisitUpdateSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InviteUser operation middleware
func (sh *strictHandler) InviteUser(w http.ResponseWriter, r *http.Request) {
	var request InviteUserRequestObject

	var body InviteUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InviteUser(ctx, request.(InviteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InviteUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InviteUserResponseObject); ok {
		if err := validResponse.VisitInviteUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableUser operation middleware
func (sh *strictHandler) DisableUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DisableUserRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableUser(ctx, request.(DisableUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableUserResponseObject); ok {
		if err := validResponse.VisitDisableUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUser operation middleware
func (sh *strictHandler) UpdateUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateUserRequestObject

	request.Id = id

	var body UpdateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUser(ctx, request.(UpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateUserResponseObject); ok {
		if err := validResponse.VisitUpdateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
