package main

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"time"
)

// checker is what /healthz needs from a backing service: a name, and something
// that answers with a version or fails. Declared here, in the consumer, so
// internal/db and internal/queue stay unaware of the health endpoint.
type checker struct {
	name    string
	version func(ctx context.Context) (string, error)
}

type serviceStatus struct {
	Status  string `json:"status"`
	Version string `json:"version,omitempty"`
	Error   string `json:"error,omitempty"`
}

type healthResponse struct {
	Status   string                   `json:"status"`
	Services map[string]serviceStatus `json:"services"`
}

// newHealthHandler reports whether every backing service is reachable, and
// which version of each actually answered.
//
// This is deliberately not a contract endpoint: /healthz is absent from
// openapi.yaml, so it is neither generated by oapi-codegen (P1-005) nor bound
// by the RFC 9457 error envelope (P1-013). A 503 here is plain JSON.
//
// ponytail: the response names software versions, which is free
// reconnaissance once the box is public. Caddy must keep /healthz internal, or
// strip the versions, before P1-001 exposes it.
func newHealthHandler(checks ...checker) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Bounded independently of the client: a hung database must not hold
		// the connection open for as long as the caller is willing to wait.
		ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
		defer cancel()

		body := healthResponse{
			Status:   "ok",
			Services: make(map[string]serviceStatus, len(checks)),
		}
		for _, c := range checks {
			version, err := c.version(ctx)
			if err != nil {
				body.Status = "degraded"
				body.Services[c.name] = serviceStatus{Status: "down", Error: err.Error()}
				continue
			}
			body.Services[c.name] = serviceStatus{Status: "ok", Version: version}
		}

		w.Header().Set("Content-Type", "application/json")
		if body.Status != "ok" {
			w.WriteHeader(http.StatusServiceUnavailable)
		}
		if err := json.NewEncoder(w).Encode(body); err != nil {
			slog.ErrorContext(ctx, "write healthz response", "error", err)
		}
	})
}
