package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"time"
)

// checker is what /healthz needs from a backing service: a name, and something
// that answers with a version or fails. Declared here, in the consumer, so
// internal/db and internal/queue stay unaware of the health endpoint.
type checker struct {
	name    string
	version func(ctx context.Context) (string, error)
}

type serviceStatus struct {
	Status  string `json:"status"`
	Version string `json:"version,omitempty"`
	Error   string `json:"error,omitempty"`
}

type healthResponse struct {
	Status   string                   `json:"status"`
	Services map[string]serviceStatus `json:"services"`
}

// newHealthHandler reports whether every backing service is reachable, and
// which version of each actually answered.
//
// This is deliberately not a contract endpoint: /healthz is absent from
// openapi.yaml, so it is neither generated by oapi-codegen (P1-005) nor bound
// by the RFC 9457 error envelope (P1-013). A 503 here is plain JSON.
//
// ponytail: the response names software versions, which is free
// reconnaissance once the box is public. Caddy must keep /healthz internal, or
// strip the versions, before P1-001 exposes it.
func newHealthHandler(checks ...checker) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Bounded independently of the client: a hung database must not hold
		// the connection open for as long as the caller is willing to wait.
		ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
		defer cancel()

		body := healthResponse{
			Status:   "ok",
			Services: make(map[string]serviceStatus, len(checks)),
		}
		for _, c := range checks {
			version, err := c.version(ctx)
			if err != nil {
				body.Status = "degraded"
				body.Services[c.name] = serviceStatus{Status: "down", Error: err.Error()}
				continue
			}
			body.Services[c.name] = serviceStatus{Status: "ok", Version: version}
		}

		w.Header().Set("Content-Type", "application/json")
		if body.Status != "ok" {
			w.WriteHeader(http.StatusServiceUnavailable)
		}
		if err := json.NewEncoder(w).Encode(body); err != nil {
			slog.ErrorContext(ctx, "write healthz response", "error", err)
		}
	})
}

// objectStoreChecker reports whether the local MinIO is answering.
//
// A plain GET, not a signed request: liveness does not need credentials, and
// the S3 adapter that would supply them is S1-033's, in M3. Pulling it forward
// to colour one line of /healthz would be building the adapter early to avoid
// writing ten lines.
//
// ponytail: /minio/health/live is MinIO's own endpoint and R2 does not serve
// it, so this probe is local-only -- which is all S1-001 asks for, since
// production has no MinIO. S1-033 replaces it with a signed HeadBucket that
// works against both.
func objectStoreChecker(baseURL string) checker {
	return checker{
		name: "objectstore",
		version: func(ctx context.Context) (string, error) {
			req, err := http.NewRequestWithContext(ctx, http.MethodGet, baseURL+"/minio/health/live", nil)
			if err != nil {
				return "", err
			}
			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				return "", err
			}
			defer func() { _ = resp.Body.Close() }()

			if resp.StatusCode != http.StatusOK {
				return "", fmt.Errorf("object store health returned %s", resp.Status)
			}
			// MinIO reports its product, not its build, and that is the right
			// amount: see the note above about /healthz being reconnaissance.
			if server := resp.Header.Get("Server"); server != "" {
				return server, nil
			}
			return "ok", nil
		},
	}
}
