// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, owner_id, user_id, token_hash, rotated_from, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.OwnerID,
		arg.UserID,
		arg.TokenHash,
		arg.RotatedFrom,
		arg.ExpiresAt,
	)
	return err
}

const getSession = `-- name: GetSession :one

SELECT u.id AS user_id, u.name AS user_name, u.role, u.status, u.email_verified_at,
       o.id AS owner_id, o.name AS owner_name, o.slug, o.business_type
  FROM users u
  JOIN owners o ON o.id = u.owner_id
 WHERE u.id = $1
`

type GetSessionRow struct {
	UserID          uuid.UUID
	UserName        string
	Role            string
	Status          string
	EmailVerifiedAt *time.Time
	OwnerID         uuid.UUID
	OwnerName       string
	Slug            *string
	BusinessType    string
}

// Queries over the identity tables. Every one of these runs INSIDE InOwnerTx.
//
// The two reads that run BEFORE a rental is known are not here. They are
// hand-written in internal/db/auth_lookup.go so that the only two reads in the
// system that reach past owner scoping are visible as such, rather than sitting
// among generated code that all looks alike.
// Everything the Session response needs, in one round trip. Runs inside
// InOwnerTx, so RLS has already scoped users; owners has no RLS by design.
//
// u.status is here for Refresh, not for the response body. Login checks the
// status against auth_lookup_user, but Refresh reached this row for the role
// alone and never looked -- so a disabled account kept minting access tokens
// every 15 minutes, forever. BR-004 caps a revoked session at the access token
// TTL, and that promise needs the column (S1-010).
func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.OwnerID,
		&i.OwnerName,
		&i.Slug,
		&i.BusinessType,
	)
	return i, err
}

const hasSuccessor = `-- name: HasSuccessor :one
SELECT EXISTS (SELECT 1 FROM refresh_tokens WHERE rotated_from = $1)
`

// Whether some other token was created by rotating this one.
//
// This is what separates theft from an ordinary sign-out. Both leave a token
// with revoked_at set, so revoked_at alone cannot tell them apart -- and
// treating a sign-out as theft means a stale browser tab replaying its old
// cookie signs the user out of every other device.
func (q *Queries) HasSuccessor(ctx context.Context, rotatedFrom *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuccessor, rotatedFrom)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertApiKey = `-- name: InsertApiKey :one
INSERT INTO api_keys (id, owner_id, name, key_prefix, key_hash, rate_limit_per_min, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, key_prefix, rate_limit_per_min, last_used_at, revoked_at, created_at
`

type InsertApiKeyParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Name            string
	KeyPrefix       string
	KeyHash         string
	RateLimitPerMin int32
	CreatedBy       *uuid.UUID
}

type InsertApiKeyRow struct {
	ID              uuid.UUID
	Name            string
	KeyPrefix       string
	RateLimitPerMin int32
	LastUsedAt      *time.Time
	RevokedAt       *time.Time
	CreatedAt       time.Time
}

// S1-079. The secret never reaches this table: key_hash is argon2id.
func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (InsertApiKeyRow, error) {
	row := q.db.QueryRow(ctx, insertApiKey,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.RateLimitPerMin,
		arg.CreatedBy,
	)
	var i InsertApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.RateLimitPerMin,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, key_prefix, rate_limit_per_min, last_used_at, revoked_at, created_at
  FROM api_keys
 ORDER BY created_at DESC
`

type ListApiKeysRow struct {
	ID              uuid.UUID
	Name            string
	KeyPrefix       string
	RateLimitPerMin int32
	LastUsedAt      *time.Time
	RevokedAt       *time.Time
	CreatedAt       time.Time
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysRow
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.RateLimitPerMin,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :execrows
UPDATE refresh_tokens SET revoked_at = now()
 WHERE user_id = $1 AND revoked_at IS NULL
`

// Used when an already-rotated token is presented again, which means it was
// stolen: the whole rotation chain is revoked and the user is signed out
// everywhere (../docs/04-api-spec.md 3.1).
//
// This revokes every active token for the user, not only the chain the reused
// token belongs to. A chain starts at each login, so a user signed in on a
// phone and a laptop has two -- and revoking one of them would leave the
// thief's other session alive while claiming the user was signed out
// everywhere. The chain is a subset of this.
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeApiKey = `-- name: RevokeApiKey :execrows
UPDATE api_keys SET revoked_at = COALESCE(revoked_at, now()) WHERE id = $1
`

// Revoked, never deleted (BR-031). Revoking twice is still revoked.
func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeApiKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = now()
 WHERE id = $1 AND revoked_at IS NULL
`

// One token, by id. Used by logout, which has no reason to touch any other.
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchApiKey = `-- name: TouchApiKey :exec
UPDATE api_keys SET last_used_at = now()
 WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// last_used_at, at most once a minute per key: a write per request would turn
// every public read into a row lock.
func (q *Queries) TouchApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchApiKey, id)
	return err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}
