// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings SET status = 'cancelled', cancelled_reason = 'manual', updated_at = now()
 WHERE id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBooking, id)
	return err
}

const cancelInvoice = `-- name: CancelInvoice :exec
UPDATE invoices SET status = 'cancelled', updated_at = now() WHERE id = $1
`

func (q *Queries) CancelInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelInvoice, id)
	return err
}

const cancelInvoicesOfBookings = `-- name: CancelInvoicesOfBookings :exec
UPDATE invoices SET status = 'cancelled', updated_at = now()
 WHERE booking_id = ANY($1::uuid[])
   AND status IN ('unpaid', 'gateway_pending', 'overdue') AND deleted_at IS NULL
`

func (q *Queries) CancelInvoicesOfBookings(ctx context.Context, bookingIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelInvoicesOfBookings, bookingIds)
	return err
}

const completeBooking = `-- name: CompleteBooking :exec
UPDATE bookings SET status = 'completed', updated_at = now() WHERE id = $1
`

func (q *Queries) CompleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeBooking, id)
	return err
}

const confirmBooking = `-- name: ConfirmBooking :exec
UPDATE bookings SET status = 'reserved', expires_at = NULL, updated_at = now()
 WHERE id = $1
`

func (q *Queries) ConfirmBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmBooking, id)
	return err
}

const deleteDepositLine = `-- name: DeleteDepositLine :execrows
DELETE FROM invoice_lines WHERE invoice_id = $1 AND kind = 'deposit'
`

// BR-051: the line is removed, not offset with a discount -- a discount counts
// as revenue (BR-076), and offsetting would shrink revenue by the deposit.
func (q *Queries) DeleteDepositLine(ctx context.Context, invoiceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepositLine, invoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const depositInvoice = `-- name: DepositInvoice :one
SELECT i.id, i.status
  FROM invoices i
  JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind = 'deposit'
 WHERE i.booking_id = $1 AND i.deleted_at IS NULL
 LIMIT 1
`

type DepositInvoiceRow struct {
	ID     uuid.UUID
	Status string
}

// The invoice carrying the deposit line, and whether it is paid -- "the money
// is in the owner's hands" (BR-048) or "can still be waived" (BR-051).
func (q *Queries) DepositInvoice(ctx context.Context, bookingID *uuid.UUID) (DepositInvoiceRow, error) {
	row := q.db.QueryRow(ctx, depositInvoice, bookingID)
	var i DepositInvoiceRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const expireDrafts = `-- name: ExpireDrafts :many

UPDATE bookings b SET status = 'cancelled', cancelled_reason = 'expired', updated_at = now()
 WHERE b.status = 'draft' AND b.expires_at IS NOT NULL AND b.expires_at < $1::timestamptz
   AND b.deleted_at IS NULL
   AND NOT EXISTS (SELECT 1 FROM handovers h WHERE h.booking_id = b.id)
RETURNING b.id
`

// ── S1-052: kedaluwarsa. Set-based, conditional, idempotent: a second run
// finds nothing left to change. None of them touches a booking that already
// has a handovers row (BR-057) -- once the unit has moved, only a person
// decides what happens next.
// BR-027: a draft past its expires_at is cancelled 'expired'. Drafts never
// carry an invoice, so nothing else moves.
func (q *Queries) ExpireDrafts(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expireDrafts, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireUnpaidReserved = `-- name: ExpireUnpaidReserved :many
UPDATE bookings b SET status = 'cancelled', cancelled_reason = 'payment_expired', updated_at = now()
  FROM owners o
 WHERE o.id = b.owner_id AND o.require_payment_before_pickup
   AND b.status = 'reserved' AND b.deleted_at IS NULL
   AND NOT EXISTS (SELECT 1 FROM handovers h WHERE h.booking_id = b.id)
   AND EXISTS (SELECT 1 FROM invoices i
                 JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind = 'rent'
                WHERE i.booking_id = b.id AND i.deleted_at IS NULL
                  AND i.status IN ('unpaid', 'overdue') AND i.due_at < $1::timestamptz)
RETURNING b.id
`

// BR-057 + BR-038, switch ON: reserved, rent invoice still unpaid past its
// due_at -> cancelled 'payment_expired'. The caller cancels the unpaid
// invoices through CancelInvoicesOfBookings -- the same rule as a manual
// cancel (BR-057 revision 3 Oct). Switch OFF never reaches here.
func (q *Queries) ExpireUnpaidReserved(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expireUnpaidReserved, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConflicts = `-- name: FindConflicts :many
SELECT code, start_at, end_at, status
  FROM bookings
 WHERE resource_unit_id = $1
   AND id <> $2
   AND status IN ('reserved', 'picked_up') AND deleted_at IS NULL
   AND start_at < $3::timestamptz
                  + make_interval(mins => $4::int)
   AND end_at_with_buffer > $5::timestamptz
 ORDER BY start_at
`

type FindConflictsParams struct {
	UnitID        uuid.UUID
	ExcludeID     uuid.UUID
	EndAt         time.Time
	BufferMinutes int32
	StartAt       time.Time
}

type FindConflictsRow struct {
	Code    string
	StartAt time.Time
	EndAt   time.Time
	Status  string
}

// The same overlap bookings_no_overlap tests, so the readable answer and the
// constraint's answer agree: both ranges carry their own buffer. Written as two
// comparisons, not tstzrange &&, so RLS lets it use an index -- see
// bookings_unit_start in 000013. [a, b) and [c, d) overlap iff a < d AND c < b. Used before
// writing (for the message) and after losing the race (for the list).
func (q *Queries) FindConflicts(ctx context.Context, arg FindConflictsParams) ([]FindConflictsRow, error) {
	rows, err := q.db.Query(ctx, findConflicts,
		arg.UnitID,
		arg.ExcludeID,
		arg.EndAt,
		arg.BufferMinutes,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConflictsRow
	for rows.Next() {
		var i FindConflictsRow
		if err := rows.Scan(
			&i.Code,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPhysicalConflicts = `-- name: FindPhysicalConflicts :many
SELECT code, start_at, end_at, status
  FROM bookings
 WHERE resource_unit_id = $1 AND id <> $2
   AND status = 'picked_up' AND end_at < now() AND deleted_at IS NULL
 ORDER BY start_at
`

type FindPhysicalConflictsParams struct {
	UnitID    uuid.UUID
	ExcludeID uuid.UUID
}

type FindPhysicalConflictsRow struct {
	Code    string
	StartAt time.Time
	EndAt   time.Time
	Status  string
}

// BR-042: the unit is still out with an earlier booking past its end. The
// schedule does not clash -- bookings_no_overlap compared ranges that have
// already ended -- but the car is not in the yard. Plain timestamptz
// comparison, not a range, for the RLS reason in 000013.
func (q *Queries) FindPhysicalConflicts(ctx context.Context, arg FindPhysicalConflictsParams) ([]FindPhysicalConflictsRow, error) {
	rows, err := q.db.Query(ctx, findPhysicalConflicts, arg.UnitID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPhysicalConflictsRow
	for rows.Next() {
		var i FindPhysicalConflictsRow
		if err := rows.Scan(
			&i.Code,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookableUnit = `-- name: GetBookableUnit :one
SELECT u.id AS unit_id, u.resource_id, u.status AS unit_status,
       r.status AS resource_status, r.base_price, r.pricing_unit, r.buffer_minutes,
       r.deposit_amount, r.late_fee_per_unit, r.min_duration, r.max_duration
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.id = $1 AND u.deleted_at IS NULL AND r.deleted_at IS NULL
`

type GetBookableUnitRow struct {
	UnitID         uuid.UUID
	ResourceID     uuid.UUID
	UnitStatus     string
	ResourceStatus string
	BasePrice      int64
	PricingUnit    string
	BufferMinutes  int32
	DepositAmount  *int64
	LateFeePerUnit *int64
	MinDuration    *int32
	MaxDuration    *int32
}

// Everything a booking snapshots, read in the same transaction it is written
// in (BR-014, BR-015, BR-016).
func (q *Queries) GetBookableUnit(ctx context.Context, id uuid.UUID) (GetBookableUnitRow, error) {
	row := q.db.QueryRow(ctx, getBookableUnit, id)
	var i GetBookableUnitRow
	err := row.Scan(
		&i.UnitID,
		&i.ResourceID,
		&i.UnitStatus,
		&i.ResourceStatus,
		&i.BasePrice,
		&i.PricingUnit,
		&i.BufferMinutes,
		&i.DepositAmount,
		&i.LateFeePerUnit,
		&i.MinDuration,
		&i.MaxDuration,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT b.id, b.code, b.status, b.source, b.start_at, b.end_at, b.end_at_with_buffer,
       b.unit_price, b.pricing_unit, b.buffer_minutes, b.duration_qty, b.subtotal,
       b.deposit_amount, b.late_fee_per_unit, b.cancelled_reason, b.expires_at,
       b.created_at, b.actual_return_at, b.deposit_waived_at, b.deposit_settled_at,
       b.deposit_deducted, b.deposit_refunded,
       (b.status = 'picked_up' AND b.end_at < now())::boolean AS overdue,
       c.id AS customer_id, c.name AS customer_name, c.phone AS customer_phone,
       c.is_blacklisted AS customer_blacklisted,
       r.id AS resource_id, r.name AS resource_name,
       u.id AS unit_id, u.code AS unit_code, u.label AS unit_label,
       pay.n_active, pay.n_overdue, pay.n_unpaid, pay.outstanding,
       b.owner_id, o.slug AS owner_slug
  FROM bookings b
  -- owners has no RLS; the join only reads this booking's own owner, for the
  -- portal link (Booking.portal_url, 04-api-spec.md §5).
  JOIN owners o         ON o.id = b.owner_id
  JOIN customers c      ON c.id = b.customer_id
  JOIN resources r      ON r.id = b.resource_id
  JOIN resource_units u ON u.id = b.resource_unit_id
  -- Ringkasan bayar, dihitung saat dibaca seperti kolom overdue (ide
  -- booking-invoice-lists): cancelled diabaikan, gateway_pending = belum bayar.
  -- ponytail: sum baris per invoice di dalam lateral tanpa index baru --
  -- invoices_owner_booking menjangkarnya; ANALYZE kalau perf test protes.
  CROSS JOIN LATERAL (
    SELECT count(*)::int AS n_active,
           (count(*) FILTER (WHERE i.status = 'overdue'))::int AS n_overdue,
           (count(*) FILTER (WHERE i.status IN ('unpaid', 'gateway_pending')))::int AS n_unpaid,
           COALESCE(sum((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id))
                      FILTER (WHERE i.status IN ('unpaid', 'gateway_pending', 'overdue')), 0)::bigint AS outstanding
      FROM invoices i
     WHERE i.booking_id = b.id AND i.status <> 'cancelled' AND i.deleted_at IS NULL
  ) pay
 WHERE b.id = $1 AND b.deleted_at IS NULL
`

type GetBookingRow struct {
	ID                  uuid.UUID
	Code                string
	Status              string
	Source              string
	StartAt             time.Time
	EndAt               time.Time
	EndAtWithBuffer     time.Time
	UnitPrice           int64
	PricingUnit         string
	BufferMinutes       int32
	DurationQty         int32
	Subtotal            int64
	DepositAmount       *int64
	LateFeePerUnit      *int64
	CancelledReason     *string
	ExpiresAt           *time.Time
	CreatedAt           time.Time
	ActualReturnAt      *time.Time
	DepositWaivedAt     *time.Time
	DepositSettledAt    *time.Time
	DepositDeducted     int64
	DepositRefunded     int64
	Overdue             bool
	CustomerID          uuid.UUID
	CustomerName        string
	CustomerPhone       string
	CustomerBlacklisted bool
	ResourceID          uuid.UUID
	ResourceName        string
	UnitID              uuid.UUID
	UnitCode            string
	UnitLabel           *string
	NActive             int32
	NOverdue            int32
	NUnpaid             int32
	Outstanding         int64
	OwnerID             uuid.UUID
	OwnerSlug           *string
}

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Source,
		&i.StartAt,
		&i.EndAt,
		&i.EndAtWithBuffer,
		&i.UnitPrice,
		&i.PricingUnit,
		&i.BufferMinutes,
		&i.DurationQty,
		&i.Subtotal,
		&i.DepositAmount,
		&i.LateFeePerUnit,
		&i.CancelledReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ActualReturnAt,
		&i.DepositWaivedAt,
		&i.DepositSettledAt,
		&i.DepositDeducted,
		&i.DepositRefunded,
		&i.Overdue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerBlacklisted,
		&i.ResourceID,
		&i.ResourceName,
		&i.UnitID,
		&i.UnitCode,
		&i.UnitLabel,
		&i.NActive,
		&i.NOverdue,
		&i.NUnpaid,
		&i.Outstanding,
		&i.OwnerID,
		&i.OwnerSlug,
	)
	return i, err
}

const getBookingCodePrefix = `-- name: GetBookingCodePrefix :one
SELECT booking_code_prefix FROM owners WHERE id = $1
`

// owners has no RLS, hence the explicit WHERE. Read at the moment the code is
// made: changing the prefix later never rewrites an old code (BR-024).
func (q *Queries) GetBookingCodePrefix(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookingCodePrefix, id)
	var booking_code_prefix string
	err := row.Scan(&booking_code_prefix)
	return booking_code_prefix, err
}

const getCustomerBlacklisted = `-- name: GetCustomerBlacklisted :one
SELECT is_blacklisted FROM customers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerBlacklisted(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCustomerBlacklisted, id)
	var is_blacklisted bool
	err := row.Scan(&is_blacklisted)
	return is_blacklisted, err
}

const getDraftExpiryHours = `-- name: GetDraftExpiryHours :one
SELECT draft_expiry_hours FROM owners WHERE id = $1
`

// BR-027: a public draft's life, per owner. owners has no RLS, hence the WHERE.
func (q *Queries) GetDraftExpiryHours(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getDraftExpiryHours, id)
	var draft_expiry_hours int32
	err := row.Scan(&draft_expiry_hours)
	return draft_expiry_hours, err
}

const insertBooking = `-- name: InsertBooking :exec
INSERT INTO bookings (id, owner_id, created_by, code, customer_id, resource_id,
                      resource_unit_id, start_at, end_at,
                      status, source, unit_price, pricing_unit, buffer_minutes,
                      duration_qty, subtotal, deposit_amount, late_fee_per_unit,
                      expires_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9,
        $10, $11, $12,
        $13, $14, $15,
        $16, $17, $18,
        $19)
`

type InsertBookingParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	CreatedBy      *uuid.UUID
	Code           string
	CustomerID     uuid.UUID
	ResourceID     uuid.UUID
	ResourceUnitID uuid.UUID
	StartAt        time.Time
	EndAt          time.Time
	Status         string
	Source         string
	UnitPrice      int64
	PricingUnit    string
	BufferMinutes  int32
	DurationQty    int32
	Subtotal       int64
	DepositAmount  *int64
	LateFeePerUnit *int64
	ExpiresAt      *time.Time
}

// end_at_with_buffer is not in the column list: the BEFORE trigger fills it,
// and NOT NULL is checked after BEFORE triggers run.
func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) error {
	_, err := q.db.Exec(ctx, insertBooking,
		arg.ID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Code,
		arg.CustomerID,
		arg.ResourceID,
		arg.ResourceUnitID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.Source,
		arg.UnitPrice,
		arg.PricingUnit,
		arg.BufferMinutes,
		arg.DurationQty,
		arg.Subtotal,
		arg.DepositAmount,
		arg.LateFeePerUnit,
		arg.ExpiresAt,
	)
	return err
}

const listAvailableUnits = `-- name: ListAvailableUnits :many
SELECT u.id, u.resource_id, u.code, u.label
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.status = 'active' AND u.deleted_at IS NULL
   AND r.status = 'active' AND r.deleted_at IS NULL
   AND ($1::uuid IS NULL OR u.resource_id = $1::uuid)
   AND NOT EXISTS (
       SELECT 1 FROM bookings b
        WHERE b.resource_unit_id = u.id
          AND b.status IN ('reserved', 'picked_up') AND b.deleted_at IS NULL
          AND b.start_at < $2::timestamptz + make_interval(mins => r.buffer_minutes)
          AND b.end_at_with_buffer > $3::timestamptz)
 ORDER BY u.code
`

type ListAvailableUnitsParams struct {
	ResourceID *uuid.UUID
	EndAt      time.Time
	StartAt    time.Time
}

type ListAvailableUnitsRow struct {
	ID         uuid.UUID
	ResourceID uuid.UUID
	Code       string
	Label      *string
}

// BR-020, with one deliberate widening: the requested range carries the
// resource's own buffer, exactly as the booking would once written. Without it
// a unit could be offered here and then refused by bookings_no_overlap -- the
// screen and the constraint must give the same answer.
func (q *Queries) ListAvailableUnits(ctx context.Context, arg ListAvailableUnitsParams) ([]ListAvailableUnitsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableUnits, arg.ResourceID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableUnitsRow
	for rows.Next() {
		var i ListAvailableUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Code,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookableResources = `-- name: ListBookableResources :many
SELECT id, name, base_price, pricing_unit, deposit_amount, buffer_minutes
  FROM resources
 WHERE status = 'active' AND deleted_at IS NULL
   AND ($1::uuid IS NULL OR id = $1::uuid)
 ORDER BY name
`

type ListBookableResourcesRow struct {
	ID            uuid.UUID
	Name          string
	BasePrice     int64
	PricingUnit   string
	DepositAmount *int64
	BufferMinutes int32
}

func (q *Queries) ListBookableResources(ctx context.Context, resourceID *uuid.UUID) ([]ListBookableResourcesRow, error) {
	rows, err := q.db.Query(ctx, listBookableResources, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookableResourcesRow
	for rows.Next() {
		var i ListBookableResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BasePrice,
			&i.PricingUnit,
			&i.DepositAmount,
			&i.BufferMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT b.id, b.code, b.status, b.source, b.start_at, b.end_at, b.end_at_with_buffer,
       b.unit_price, b.pricing_unit, b.buffer_minutes, b.duration_qty, b.subtotal,
       b.deposit_amount, b.late_fee_per_unit, b.cancelled_reason, b.expires_at,
       b.created_at, b.actual_return_at, b.deposit_waived_at, b.deposit_settled_at,
       b.deposit_deducted, b.deposit_refunded,
       (b.status = 'picked_up' AND b.end_at < now())::boolean AS overdue,
       c.id AS customer_id, c.name AS customer_name, c.phone AS customer_phone,
       c.is_blacklisted AS customer_blacklisted,
       r.id AS resource_id, r.name AS resource_name,
       u.id AS unit_id, u.code AS unit_code, u.label AS unit_label,
       pay.n_active, pay.n_overdue, pay.n_unpaid, pay.outstanding,
       b.owner_id, o.slug AS owner_slug
  FROM bookings b
  -- owners has no RLS; the join only reads this booking's own owner, for the
  -- portal link (Booking.portal_url, 04-api-spec.md §5).
  JOIN owners o         ON o.id = b.owner_id
  JOIN customers c      ON c.id = b.customer_id
  JOIN resources r      ON r.id = b.resource_id
  JOIN resource_units u ON u.id = b.resource_unit_id
  -- Ringkasan bayar, dihitung saat dibaca seperti kolom overdue (ide
  -- booking-invoice-lists): cancelled diabaikan, gateway_pending = belum bayar.
  -- ponytail: sum baris per invoice di dalam lateral tanpa index baru --
  -- invoices_owner_booking menjangkarnya; ANALYZE kalau perf test protes.
  CROSS JOIN LATERAL (
    SELECT count(*)::int AS n_active,
           (count(*) FILTER (WHERE i.status = 'overdue'))::int AS n_overdue,
           (count(*) FILTER (WHERE i.status IN ('unpaid', 'gateway_pending')))::int AS n_unpaid,
           COALESCE(sum((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id))
                      FILTER (WHERE i.status IN ('unpaid', 'gateway_pending', 'overdue')), 0)::bigint AS outstanding
      FROM invoices i
     WHERE i.booking_id = b.id AND i.status <> 'cancelled' AND i.deleted_at IS NULL
  ) pay
 WHERE b.deleted_at IS NULL
   AND ($1::text IS NULL OR b.status = $1::text)
   AND ($2::timestamptz IS NULL OR b.end_at > $2::timestamptz)
   AND ($3::timestamptz IS NULL OR b.start_at < $3::timestamptz)
   AND ($4::uuid[] IS NULL OR b.resource_unit_id = ANY($4::uuid[]))
   AND ($5::uuid[] IS NULL OR b.customer_id = ANY($5::uuid[]))
   AND ($6::uuid[] IS NULL OR b.resource_id = ANY($6::uuid[]))
   -- strpos, not ILIKE: a '%' or '_' the user typed is a character, not a wildcard.
   AND ($7::text IS NULL OR strpos(lower(b.code), lower($7::text)) > 0)
   AND (NOT $8::boolean
        OR (b.status = 'picked_up' AND b.end_at < now()))
   AND ($9::timestamptz IS NULL
        OR (b.start_at, b.id) < ($9::timestamptz, $10::uuid))
 ORDER BY b.start_at DESC, b.id DESC
 LIMIT $11
`

type ListBookingsParams struct {
	Status      *string
	FromAt      *time.Time
	ToAt        *time.Time
	UnitIds     []uuid.UUID
	CustomerIds []uuid.UUID
	ResourceIds []uuid.UUID
	Code        *string
	OverdueOnly bool
	CursorStart *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListBookingsRow struct {
	ID                  uuid.UUID
	Code                string
	Status              string
	Source              string
	StartAt             time.Time
	EndAt               time.Time
	EndAtWithBuffer     time.Time
	UnitPrice           int64
	PricingUnit         string
	BufferMinutes       int32
	DurationQty         int32
	Subtotal            int64
	DepositAmount       *int64
	LateFeePerUnit      *int64
	CancelledReason     *string
	ExpiresAt           *time.Time
	CreatedAt           time.Time
	ActualReturnAt      *time.Time
	DepositWaivedAt     *time.Time
	DepositSettledAt    *time.Time
	DepositDeducted     int64
	DepositRefunded     int64
	Overdue             bool
	CustomerID          uuid.UUID
	CustomerName        string
	CustomerPhone       string
	CustomerBlacklisted bool
	ResourceID          uuid.UUID
	ResourceName        string
	UnitID              uuid.UUID
	UnitCode            string
	UnitLabel           *string
	NActive             int32
	NOverdue            int32
	NUnpaid             int32
	Outstanding         int64
	OwnerID             uuid.UUID
	OwnerSlug           *string
}

// from/to select bookings that OVERLAP the window, not ones that start in it.
// overdue is derived, never stored (BR-041). Keyset on (start_at, id).
// ponytail: code is a substring scan with no index -- fine inside one
// owner's RLS slice; add pg_trgm if a fleet ever makes this slow.
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.Status,
		arg.FromAt,
		arg.ToAt,
		arg.UnitIds,
		arg.CustomerIds,
		arg.ResourceIds,
		arg.Code,
		arg.OverdueOnly,
		arg.CursorStart,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.Source,
			&i.StartAt,
			&i.EndAt,
			&i.EndAtWithBuffer,
			&i.UnitPrice,
			&i.PricingUnit,
			&i.BufferMinutes,
			&i.DurationQty,
			&i.Subtotal,
			&i.DepositAmount,
			&i.LateFeePerUnit,
			&i.CancelledReason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ActualReturnAt,
			&i.DepositWaivedAt,
			&i.DepositSettledAt,
			&i.DepositDeducted,
			&i.DepositRefunded,
			&i.Overdue,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerBlacklisted,
			&i.ResourceID,
			&i.ResourceName,
			&i.UnitID,
			&i.UnitCode,
			&i.UnitLabel,
			&i.NActive,
			&i.NOverdue,
			&i.NUnpaid,
			&i.Outstanding,
			&i.OwnerID,
			&i.OwnerSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarBookings = `-- name: ListCalendarBookings :many
SELECT b.id, b.code, b.resource_unit_id, b.start_at, b.end_at, b.end_at_with_buffer,
       b.status, c.name AS customer_name,
       -- reserved_paid vs reserved_unpaid (BR-033): the rent invoice's status.
       EXISTS (SELECT 1 FROM invoices i
                 JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind = 'rent'
                WHERE i.booking_id = b.id AND i.status = 'paid')::boolean AS rent_paid
  FROM bookings b
  JOIN customers c ON c.id = b.customer_id
 WHERE b.status IN ('reserved', 'picked_up') AND b.deleted_at IS NULL
   AND b.start_at < $1::timestamptz
   AND b.end_at_with_buffer > $2::timestamptz
 ORDER BY b.resource_unit_id, b.start_at
`

type ListCalendarBookingsParams struct {
	ToAt   time.Time
	FromAt time.Time
}

type ListCalendarBookingsRow struct {
	ID              uuid.UUID
	Code            string
	ResourceUnitID  uuid.UUID
	StartAt         time.Time
	EndAt           time.Time
	EndAtWithBuffer time.Time
	Status          string
	CustomerName    string
	RentPaid        bool
}

// Only the two statuses that lock (BR-023): draft never appears, returned shows
// as available.
func (q *Queries) ListCalendarBookings(ctx context.Context, arg ListCalendarBookingsParams) ([]ListCalendarBookingsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarBookings, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarBookingsRow
	for rows.Next() {
		var i ListCalendarBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ResourceUnitID,
			&i.StartAt,
			&i.EndAt,
			&i.EndAtWithBuffer,
			&i.Status,
			&i.CustomerName,
			&i.RentPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarUnits = `-- name: ListCalendarUnits :many
SELECT u.id, u.resource_id, u.code, u.label, u.status
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.deleted_at IS NULL AND u.status <> 'retired' AND r.deleted_at IS NULL
 ORDER BY r.name, u.code
`

type ListCalendarUnitsRow struct {
	ID         uuid.UUID
	ResourceID uuid.UUID
	Code       string
	Label      *string
	Status     string
}

// Every lane except retired (BR-033). Maintenance keeps its lane.
func (q *Queries) ListCalendarUnits(ctx context.Context) ([]ListCalendarUnitsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarUnitsRow
	for rows.Next() {
		var i ListCalendarUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Code,
			&i.Label,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT status, resource_unit_id, start_at, end_at, buffer_minutes,
       -- The snapshot Confirm issues the first invoice from (BR-045, BR-057).
       code, customer_id, pricing_unit, duration_qty, subtotal, deposit_amount
  FROM bookings
 WHERE id = $1 AND deleted_at IS NULL
   FOR UPDATE
`

type LockBookingRow struct {
	Status         string
	ResourceUnitID uuid.UUID
	StartAt        time.Time
	EndAt          time.Time
	BufferMinutes  int32
	Code           string
	CustomerID     uuid.UUID
	PricingUnit    string
	DurationQty    int32
	Subtotal       int64
	DepositAmount  *int64
}

// FOR UPDATE so a confirm, a cancel and a swap on the same booking serialise
// instead of each deciding from a status the other is about to change.
func (q *Queries) LockBooking(ctx context.Context, id uuid.UUID) (LockBookingRow, error) {
	row := q.db.QueryRow(ctx, lockBooking, id)
	var i LockBookingRow
	err := row.Scan(
		&i.Status,
		&i.ResourceUnitID,
		&i.StartAt,
		&i.EndAt,
		&i.BufferMinutes,
		&i.Code,
		&i.CustomerID,
		&i.PricingUnit,
		&i.DurationQty,
		&i.Subtotal,
		&i.DepositAmount,
	)
	return i, err
}

const lockBookingDeposit = `-- name: LockBookingDeposit :one
SELECT status, code, customer_id, deposit_amount, deposit_waived_at, deposit_settled_at
  FROM bookings
 WHERE id = $1 AND deleted_at IS NULL
   FOR UPDATE
`

type LockBookingDepositRow struct {
	Status           string
	Code             string
	CustomerID       uuid.UUID
	DepositAmount    *int64
	DepositWaivedAt  *time.Time
	DepositSettledAt *time.Time
}

func (q *Queries) LockBookingDeposit(ctx context.Context, id uuid.UUID) (LockBookingDepositRow, error) {
	row := q.db.QueryRow(ctx, lockBookingDeposit, id)
	var i LockBookingDepositRow
	err := row.Scan(
		&i.Status,
		&i.Code,
		&i.CustomerID,
		&i.DepositAmount,
		&i.DepositWaivedAt,
		&i.DepositSettledAt,
	)
	return i, err
}

const lockBookingForHandover = `-- name: LockBookingForHandover :one
SELECT b.status, b.code, b.customer_id, b.resource_unit_id, b.start_at, b.end_at,
       b.pricing_unit, b.late_fee_per_unit, b.deposit_amount,
       EXISTS (SELECT 1 FROM vehicle_specs v WHERE v.resource_id = b.resource_id)::boolean AS is_vehicle,
       o.require_payment_before_pickup
  FROM bookings b
  JOIN owners o ON o.id = b.owner_id
 WHERE b.id = $1 AND b.deleted_at IS NULL
   FOR UPDATE OF b
`

type LockBookingForHandoverRow struct {
	Status                     string
	Code                       string
	CustomerID                 uuid.UUID
	ResourceUnitID             uuid.UUID
	StartAt                    time.Time
	EndAt                      time.Time
	PricingUnit                string
	LateFeePerUnit             *int64
	DepositAmount              *int64
	IsVehicle                  bool
	RequirePaymentBeforePickup bool
}

// Everything pickup and return decide from, read under the row lock.
// is_vehicle is the "metered" rule (S1-035): a resource with vehicle specs.
func (q *Queries) LockBookingForHandover(ctx context.Context, id uuid.UUID) (LockBookingForHandoverRow, error) {
	row := q.db.QueryRow(ctx, lockBookingForHandover, id)
	var i LockBookingForHandoverRow
	err := row.Scan(
		&i.Status,
		&i.Code,
		&i.CustomerID,
		&i.ResourceUnitID,
		&i.StartAt,
		&i.EndAt,
		&i.PricingUnit,
		&i.LateFeePerUnit,
		&i.DepositAmount,
		&i.IsVehicle,
		&i.RequirePaymentBeforePickup,
	)
	return i, err
}

const markInvoicesOverdue = `-- name: MarkInvoicesOverdue :execrows
UPDATE invoices SET status = 'overdue', updated_at = now()
 WHERE status = 'unpaid' AND due_at < $1::timestamptz AND deleted_at IS NULL
`

// BR-056: unpaid past due_at is 'overdue' -- a stored invoice status, unlike a
// booking's overdue, which is derived. With the switch off this is all that
// happens to an unpaid booking (BR-038).
func (q *Queries) MarkInvoicesOverdue(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicesOverdue, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNoShows = `-- name: MarkNoShows :execrows
UPDATE bookings b SET status = 'no_show', updated_at = now()
  FROM owners o
 WHERE o.id = b.owner_id
   AND b.status = 'reserved' AND b.deleted_at IS NULL
   AND b.start_at + make_interval(hours => o.no_show_tolerance_hours) < $1::timestamptz
   AND NOT EXISTS (SELECT 1 FROM handovers h WHERE h.booking_id = b.id)
`

// BR-057: reserved and still not picked up past start_at plus the owner's
// tolerance (default 3h, may be 0). A no_show is not refused at pickup later.
func (q *Queries) MarkNoShows(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markNoShows, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPickedUp = `-- name: MarkPickedUp :exec
UPDATE bookings SET status = 'picked_up', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkPickedUp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPickedUp, id)
	return err
}

const markReturned = `-- name: MarkReturned :exec
UPDATE bookings SET status = 'returned', actual_return_at = $2, updated_at = now()
 WHERE id = $1
`

type MarkReturnedParams struct {
	ID             uuid.UUID
	ActualReturnAt *time.Time
}

// BR-040: the server's clock, never the body's -- the same instant the late
// fee was computed from, passed in so the two cannot disagree.
func (q *Queries) MarkReturned(ctx context.Context, arg MarkReturnedParams) error {
	_, err := q.db.Exec(ctx, markReturned, arg.ID, arg.ActualReturnAt)
	return err
}

const nextBookingNumber = `-- name: NextBookingNumber :one

INSERT INTO booking_counters (owner_id, last_number) VALUES ($1, 1)
ON CONFLICT (owner_id) DO UPDATE
    SET last_number = booking_counters.last_number + 1
RETURNING last_number
`

// Booking, ketersediaan, kalender.  (S1-022 .. S1-027, S1-078)
//
// Every query runs inside InOwnerTx; RLS scopes the rows. owner_id appears only
// as an INSERT value. Nothing here prevents a double booking -- that is
// bookings_no_overlap's job alone (BR-022). The conflict query below only makes
// the refusal readable.
// BR-024: never MAX(code)+1 -- two concurrent creates would read the same max.
// The upsert takes the row lock, so the second waits for the first and gets
// the next number. A deleted booking's number is never handed out again.
func (q *Queries) NextBookingNumber(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextBookingNumber, ownerID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const returnCharges = `-- name: ReturnCharges :many
SELECT l.invoice_id, l.kind, l.description, l.amount, l.handover_photo_id
  FROM invoice_lines l
  JOIN invoices i ON i.id = l.invoice_id
 WHERE i.booking_id = $1 AND i.deleted_at IS NULL AND i.status IN ('unpaid', 'overdue')
   AND l.kind IN ('late_fee', 'damage')
 ORDER BY l.created_at, l.id
`

type ReturnChargesRow struct {
	InvoiceID       uuid.UUID
	Kind            string
	Description     string
	Amount          int64
	HandoverPhotoID *uuid.UUID
}

// What the deposit absorbs at settlement: late fee and damage lines issued at
// return, on invoices not yet paid. A return invoice the renter already paid
// is settled money; absorbing it again is the double charge settle exists to
// prevent (BR-048).
func (q *Queries) ReturnCharges(ctx context.Context, bookingID *uuid.UUID) ([]ReturnChargesRow, error) {
	rows, err := q.db.Query(ctx, returnCharges, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnChargesRow
	for rows.Next() {
		var i ReturnChargesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.Kind,
			&i.Description,
			&i.Amount,
			&i.HandoverPhotoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUnitMeter = `-- name: SetUnitMeter :exec
UPDATE resource_units SET meter_value = $2, updated_at = now() WHERE id = $1
`

type SetUnitMeterParams struct {
	ID         uuid.UUID
	MeterValue *int64
}

// The handover is where the odometer gets read; the unit keeps the latest.
func (q *Queries) SetUnitMeter(ctx context.Context, arg SetUnitMeterParams) error {
	_, err := q.db.Exec(ctx, setUnitMeter, arg.ID, arg.MeterValue)
	return err
}

const settleDeposit = `-- name: SettleDeposit :exec
UPDATE bookings SET deposit_deducted = $2, deposit_refunded = $3, deposit_note = $4,
       deposit_settled_at = now(), updated_at = now()
 WHERE id = $1
`

type SettleDepositParams struct {
	ID              uuid.UUID
	DepositDeducted int64
	DepositRefunded int64
	DepositNote     *string
}

func (q *Queries) SettleDeposit(ctx context.Context, arg SettleDepositParams) error {
	_, err := q.db.Exec(ctx, settleDeposit,
		arg.ID,
		arg.DepositDeducted,
		arg.DepositRefunded,
		arg.DepositNote,
	)
	return err
}

const swapBookingUnit = `-- name: SwapBookingUnit :exec
UPDATE bookings SET resource_unit_id = $1, updated_at = now()
 WHERE id = $2
`

type SwapBookingUnitParams struct {
	UnitID uuid.UUID
	ID     uuid.UUID
}

// resource_id is untouched: bookings_unit_matches_resource refuses a unit of
// another kind, and the price snapshot stays the original resource's (BR-029).
func (q *Queries) SwapBookingUnit(ctx context.Context, arg SwapBookingUnitParams) error {
	_, err := q.db.Exec(ctx, swapBookingUnit, arg.UnitID, arg.ID)
	return err
}

const waiveDeposit = `-- name: WaiveDeposit :exec
UPDATE bookings SET deposit_waived_at = now(), deposit_waived_by = $2, deposit_waiver_reason = $3,
       updated_at = now()
 WHERE id = $1
`

type WaiveDepositParams struct {
	ID                  uuid.UUID
	DepositWaivedBy     *uuid.UUID
	DepositWaiverReason *string
}

func (q *Queries) WaiveDeposit(ctx context.Context, arg WaiveDepositParams) error {
	_, err := q.db.Exec(ctx, waiveDeposit, arg.ID, arg.DepositWaivedBy, arg.DepositWaiverReason)
	return err
}
