// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings SET status = 'cancelled', cancelled_reason = 'manual', updated_at = now()
 WHERE id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBooking, id)
	return err
}

const confirmBooking = `-- name: ConfirmBooking :exec
UPDATE bookings SET status = 'reserved', expires_at = NULL, updated_at = now()
 WHERE id = $1
`

func (q *Queries) ConfirmBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmBooking, id)
	return err
}

const findConflicts = `-- name: FindConflicts :many
SELECT code, start_at, end_at, status
  FROM bookings
 WHERE resource_unit_id = $1
   AND id <> $2
   AND status IN ('reserved', 'picked_up') AND deleted_at IS NULL
   AND start_at < $3::timestamptz
                  + make_interval(mins => $4::int)
   AND end_at_with_buffer > $5::timestamptz
 ORDER BY start_at
`

type FindConflictsParams struct {
	UnitID        uuid.UUID
	ExcludeID     uuid.UUID
	EndAt         time.Time
	BufferMinutes int32
	StartAt       time.Time
}

type FindConflictsRow struct {
	Code    string
	StartAt time.Time
	EndAt   time.Time
	Status  string
}

// The same overlap bookings_no_overlap tests, so the readable answer and the
// constraint's answer agree: both ranges carry their own buffer. Written as two
// comparisons, not tstzrange &&, so RLS lets it use an index -- see
// bookings_unit_start in 000013. [a, b) and [c, d) overlap iff a < d AND c < b. Used before
// writing (for the message) and after losing the race (for the list).
func (q *Queries) FindConflicts(ctx context.Context, arg FindConflictsParams) ([]FindConflictsRow, error) {
	rows, err := q.db.Query(ctx, findConflicts,
		arg.UnitID,
		arg.ExcludeID,
		arg.EndAt,
		arg.BufferMinutes,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConflictsRow
	for rows.Next() {
		var i FindConflictsRow
		if err := rows.Scan(
			&i.Code,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookableUnit = `-- name: GetBookableUnit :one
SELECT u.id AS unit_id, u.resource_id, u.status AS unit_status,
       r.status AS resource_status, r.base_price, r.pricing_unit, r.buffer_minutes,
       r.deposit_amount, r.late_fee_per_unit, r.min_duration, r.max_duration
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.id = $1 AND u.deleted_at IS NULL AND r.deleted_at IS NULL
`

type GetBookableUnitRow struct {
	UnitID         uuid.UUID
	ResourceID     uuid.UUID
	UnitStatus     string
	ResourceStatus string
	BasePrice      int64
	PricingUnit    string
	BufferMinutes  int32
	DepositAmount  *int64
	LateFeePerUnit *int64
	MinDuration    *int32
	MaxDuration    *int32
}

// Everything a booking snapshots, read in the same transaction it is written
// in (BR-014, BR-015, BR-016).
func (q *Queries) GetBookableUnit(ctx context.Context, id uuid.UUID) (GetBookableUnitRow, error) {
	row := q.db.QueryRow(ctx, getBookableUnit, id)
	var i GetBookableUnitRow
	err := row.Scan(
		&i.UnitID,
		&i.ResourceID,
		&i.UnitStatus,
		&i.ResourceStatus,
		&i.BasePrice,
		&i.PricingUnit,
		&i.BufferMinutes,
		&i.DepositAmount,
		&i.LateFeePerUnit,
		&i.MinDuration,
		&i.MaxDuration,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT b.id, b.code, b.status, b.source, b.start_at, b.end_at, b.end_at_with_buffer,
       b.unit_price, b.pricing_unit, b.buffer_minutes, b.duration_qty, b.subtotal,
       b.deposit_amount, b.late_fee_per_unit, b.cancelled_reason, b.expires_at,
       b.created_at,
       (b.status = 'picked_up' AND b.end_at < now())::boolean AS overdue,
       c.id AS customer_id, c.name AS customer_name, c.phone AS customer_phone,
       c.is_blacklisted AS customer_blacklisted,
       r.id AS resource_id, r.name AS resource_name,
       u.id AS unit_id, u.code AS unit_code, u.label AS unit_label
  FROM bookings b
  JOIN customers c      ON c.id = b.customer_id
  JOIN resources r      ON r.id = b.resource_id
  JOIN resource_units u ON u.id = b.resource_unit_id
 WHERE b.id = $1 AND b.deleted_at IS NULL
`

type GetBookingRow struct {
	ID                  uuid.UUID
	Code                string
	Status              string
	Source              string
	StartAt             time.Time
	EndAt               time.Time
	EndAtWithBuffer     time.Time
	UnitPrice           int64
	PricingUnit         string
	BufferMinutes       int32
	DurationQty         int32
	Subtotal            int64
	DepositAmount       *int64
	LateFeePerUnit      *int64
	CancelledReason     *string
	ExpiresAt           *time.Time
	CreatedAt           time.Time
	Overdue             bool
	CustomerID          uuid.UUID
	CustomerName        string
	CustomerPhone       string
	CustomerBlacklisted bool
	ResourceID          uuid.UUID
	ResourceName        string
	UnitID              uuid.UUID
	UnitCode            string
	UnitLabel           *string
}

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Source,
		&i.StartAt,
		&i.EndAt,
		&i.EndAtWithBuffer,
		&i.UnitPrice,
		&i.PricingUnit,
		&i.BufferMinutes,
		&i.DurationQty,
		&i.Subtotal,
		&i.DepositAmount,
		&i.LateFeePerUnit,
		&i.CancelledReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Overdue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerBlacklisted,
		&i.ResourceID,
		&i.ResourceName,
		&i.UnitID,
		&i.UnitCode,
		&i.UnitLabel,
	)
	return i, err
}

const getBookingCodePrefix = `-- name: GetBookingCodePrefix :one
SELECT booking_code_prefix FROM owners WHERE id = $1
`

// owners has no RLS, hence the explicit WHERE. Read at the moment the code is
// made: changing the prefix later never rewrites an old code (BR-024).
func (q *Queries) GetBookingCodePrefix(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookingCodePrefix, id)
	var booking_code_prefix string
	err := row.Scan(&booking_code_prefix)
	return booking_code_prefix, err
}

const getCustomerBlacklisted = `-- name: GetCustomerBlacklisted :one
SELECT is_blacklisted FROM customers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerBlacklisted(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCustomerBlacklisted, id)
	var is_blacklisted bool
	err := row.Scan(&is_blacklisted)
	return is_blacklisted, err
}

const insertBooking = `-- name: InsertBooking :exec
INSERT INTO bookings (id, owner_id, created_by, code, customer_id, resource_id,
                      resource_unit_id, start_at, end_at,
                      status, source, unit_price, pricing_unit, buffer_minutes,
                      duration_qty, subtotal, deposit_amount, late_fee_per_unit)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9,
        $10, $11, $12,
        $13, $14, $15,
        $16, $17, $18)
`

type InsertBookingParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	CreatedBy      *uuid.UUID
	Code           string
	CustomerID     uuid.UUID
	ResourceID     uuid.UUID
	ResourceUnitID uuid.UUID
	StartAt        time.Time
	EndAt          time.Time
	Status         string
	Source         string
	UnitPrice      int64
	PricingUnit    string
	BufferMinutes  int32
	DurationQty    int32
	Subtotal       int64
	DepositAmount  *int64
	LateFeePerUnit *int64
}

// end_at_with_buffer is not in the column list: the BEFORE trigger fills it,
// and NOT NULL is checked after BEFORE triggers run.
func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) error {
	_, err := q.db.Exec(ctx, insertBooking,
		arg.ID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Code,
		arg.CustomerID,
		arg.ResourceID,
		arg.ResourceUnitID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.Source,
		arg.UnitPrice,
		arg.PricingUnit,
		arg.BufferMinutes,
		arg.DurationQty,
		arg.Subtotal,
		arg.DepositAmount,
		arg.LateFeePerUnit,
	)
	return err
}

const listAvailableUnits = `-- name: ListAvailableUnits :many
SELECT u.id, u.resource_id, u.code, u.label
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.status = 'active' AND u.deleted_at IS NULL
   AND r.status = 'active' AND r.deleted_at IS NULL
   AND ($1::uuid IS NULL OR u.resource_id = $1::uuid)
   AND NOT EXISTS (
       SELECT 1 FROM bookings b
        WHERE b.resource_unit_id = u.id
          AND b.status IN ('reserved', 'picked_up') AND b.deleted_at IS NULL
          AND b.start_at < $2::timestamptz + make_interval(mins => r.buffer_minutes)
          AND b.end_at_with_buffer > $3::timestamptz)
 ORDER BY u.code
`

type ListAvailableUnitsParams struct {
	ResourceID *uuid.UUID
	EndAt      time.Time
	StartAt    time.Time
}

type ListAvailableUnitsRow struct {
	ID         uuid.UUID
	ResourceID uuid.UUID
	Code       string
	Label      *string
}

// BR-020, with one deliberate widening: the requested range carries the
// resource's own buffer, exactly as the booking would once written. Without it
// a unit could be offered here and then refused by bookings_no_overlap -- the
// screen and the constraint must give the same answer.
func (q *Queries) ListAvailableUnits(ctx context.Context, arg ListAvailableUnitsParams) ([]ListAvailableUnitsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableUnits, arg.ResourceID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableUnitsRow
	for rows.Next() {
		var i ListAvailableUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Code,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookableResources = `-- name: ListBookableResources :many
SELECT id, name, base_price, pricing_unit, deposit_amount, buffer_minutes
  FROM resources
 WHERE status = 'active' AND deleted_at IS NULL
   AND ($1::uuid IS NULL OR id = $1::uuid)
 ORDER BY name
`

type ListBookableResourcesRow struct {
	ID            uuid.UUID
	Name          string
	BasePrice     int64
	PricingUnit   string
	DepositAmount *int64
	BufferMinutes int32
}

func (q *Queries) ListBookableResources(ctx context.Context, resourceID *uuid.UUID) ([]ListBookableResourcesRow, error) {
	rows, err := q.db.Query(ctx, listBookableResources, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookableResourcesRow
	for rows.Next() {
		var i ListBookableResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BasePrice,
			&i.PricingUnit,
			&i.DepositAmount,
			&i.BufferMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT b.id, b.code, b.status, b.source, b.start_at, b.end_at, b.end_at_with_buffer,
       b.unit_price, b.pricing_unit, b.buffer_minutes, b.duration_qty, b.subtotal,
       b.deposit_amount, b.late_fee_per_unit, b.cancelled_reason, b.expires_at,
       b.created_at,
       (b.status = 'picked_up' AND b.end_at < now())::boolean AS overdue,
       c.id AS customer_id, c.name AS customer_name, c.phone AS customer_phone,
       c.is_blacklisted AS customer_blacklisted,
       r.id AS resource_id, r.name AS resource_name,
       u.id AS unit_id, u.code AS unit_code, u.label AS unit_label
  FROM bookings b
  JOIN customers c      ON c.id = b.customer_id
  JOIN resources r      ON r.id = b.resource_id
  JOIN resource_units u ON u.id = b.resource_unit_id
 WHERE b.deleted_at IS NULL
   AND ($1::text IS NULL OR b.status = $1::text)
   AND ($2::timestamptz IS NULL OR b.end_at > $2::timestamptz)
   AND ($3::timestamptz IS NULL OR b.start_at < $3::timestamptz)
   AND ($4::uuid IS NULL OR b.resource_unit_id = $4::uuid)
   AND ($5::uuid IS NULL OR b.customer_id = $5::uuid)
   AND (NOT $6::boolean
        OR (b.status = 'picked_up' AND b.end_at < now()))
   AND ($7::timestamptz IS NULL
        OR (b.start_at, b.id) < ($7::timestamptz, $8::uuid))
 ORDER BY b.start_at DESC, b.id DESC
 LIMIT $9
`

type ListBookingsParams struct {
	Status      *string
	FromAt      *time.Time
	ToAt        *time.Time
	UnitID      *uuid.UUID
	CustomerID  *uuid.UUID
	OverdueOnly bool
	CursorStart *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListBookingsRow struct {
	ID                  uuid.UUID
	Code                string
	Status              string
	Source              string
	StartAt             time.Time
	EndAt               time.Time
	EndAtWithBuffer     time.Time
	UnitPrice           int64
	PricingUnit         string
	BufferMinutes       int32
	DurationQty         int32
	Subtotal            int64
	DepositAmount       *int64
	LateFeePerUnit      *int64
	CancelledReason     *string
	ExpiresAt           *time.Time
	CreatedAt           time.Time
	Overdue             bool
	CustomerID          uuid.UUID
	CustomerName        string
	CustomerPhone       string
	CustomerBlacklisted bool
	ResourceID          uuid.UUID
	ResourceName        string
	UnitID              uuid.UUID
	UnitCode            string
	UnitLabel           *string
}

// from/to select bookings that OVERLAP the window, not ones that start in it.
// overdue is derived, never stored (BR-041). Keyset on (start_at, id).
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.Status,
		arg.FromAt,
		arg.ToAt,
		arg.UnitID,
		arg.CustomerID,
		arg.OverdueOnly,
		arg.CursorStart,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.Source,
			&i.StartAt,
			&i.EndAt,
			&i.EndAtWithBuffer,
			&i.UnitPrice,
			&i.PricingUnit,
			&i.BufferMinutes,
			&i.DurationQty,
			&i.Subtotal,
			&i.DepositAmount,
			&i.LateFeePerUnit,
			&i.CancelledReason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Overdue,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerBlacklisted,
			&i.ResourceID,
			&i.ResourceName,
			&i.UnitID,
			&i.UnitCode,
			&i.UnitLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarBookings = `-- name: ListCalendarBookings :many
SELECT b.id, b.code, b.resource_unit_id, b.start_at, b.end_at, b.end_at_with_buffer,
       b.status, c.name AS customer_name
  FROM bookings b
  JOIN customers c ON c.id = b.customer_id
 WHERE b.status IN ('reserved', 'picked_up') AND b.deleted_at IS NULL
   AND b.start_at < $1::timestamptz
   AND b.end_at_with_buffer > $2::timestamptz
 ORDER BY b.resource_unit_id, b.start_at
`

type ListCalendarBookingsParams struct {
	ToAt   time.Time
	FromAt time.Time
}

type ListCalendarBookingsRow struct {
	ID              uuid.UUID
	Code            string
	ResourceUnitID  uuid.UUID
	StartAt         time.Time
	EndAt           time.Time
	EndAtWithBuffer time.Time
	Status          string
	CustomerName    string
}

// Only the two statuses that lock (BR-023): draft never appears, returned shows
// as available.
func (q *Queries) ListCalendarBookings(ctx context.Context, arg ListCalendarBookingsParams) ([]ListCalendarBookingsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarBookings, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarBookingsRow
	for rows.Next() {
		var i ListCalendarBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ResourceUnitID,
			&i.StartAt,
			&i.EndAt,
			&i.EndAtWithBuffer,
			&i.Status,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarUnits = `-- name: ListCalendarUnits :many
SELECT u.id, u.resource_id, u.code, u.label, u.status
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id
 WHERE u.deleted_at IS NULL AND u.status <> 'retired' AND r.deleted_at IS NULL
 ORDER BY r.name, u.code
`

type ListCalendarUnitsRow struct {
	ID         uuid.UUID
	ResourceID uuid.UUID
	Code       string
	Label      *string
	Status     string
}

// Every lane except retired (BR-033). Maintenance keeps its lane.
func (q *Queries) ListCalendarUnits(ctx context.Context) ([]ListCalendarUnitsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarUnitsRow
	for rows.Next() {
		var i ListCalendarUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Code,
			&i.Label,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT status, resource_unit_id, start_at, end_at, buffer_minutes
  FROM bookings
 WHERE id = $1 AND deleted_at IS NULL
   FOR UPDATE
`

type LockBookingRow struct {
	Status         string
	ResourceUnitID uuid.UUID
	StartAt        time.Time
	EndAt          time.Time
	BufferMinutes  int32
}

// FOR UPDATE so a confirm, a cancel and a swap on the same booking serialise
// instead of each deciding from a status the other is about to change.
func (q *Queries) LockBooking(ctx context.Context, id uuid.UUID) (LockBookingRow, error) {
	row := q.db.QueryRow(ctx, lockBooking, id)
	var i LockBookingRow
	err := row.Scan(
		&i.Status,
		&i.ResourceUnitID,
		&i.StartAt,
		&i.EndAt,
		&i.BufferMinutes,
	)
	return i, err
}

const nextBookingNumber = `-- name: NextBookingNumber :one

INSERT INTO booking_counters (owner_id, last_number) VALUES ($1, 1)
ON CONFLICT (owner_id) DO UPDATE
    SET last_number = booking_counters.last_number + 1
RETURNING last_number
`

// Booking, ketersediaan, kalender.  (S1-022 .. S1-027, S1-078)
//
// Every query runs inside InOwnerTx; RLS scopes the rows. owner_id appears only
// as an INSERT value. Nothing here prevents a double booking -- that is
// bookings_no_overlap's job alone (BR-022). The conflict query below only makes
// the refusal readable.
// BR-024: never MAX(code)+1 -- two concurrent creates would read the same max.
// The upsert takes the row lock, so the second waits for the first and gets
// the next number. A deleted booking's number is never handed out again.
func (q *Queries) NextBookingNumber(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextBookingNumber, ownerID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const swapBookingUnit = `-- name: SwapBookingUnit :exec
UPDATE bookings SET resource_unit_id = $1, updated_at = now()
 WHERE id = $2
`

type SwapBookingUnitParams struct {
	UnitID uuid.UUID
	ID     uuid.UUID
}

// resource_id is untouched: bookings_unit_matches_resource refuses a unit of
// another kind, and the price snapshot stays the original resource's (BR-029).
func (q *Queries) SwapBookingUnit(ctx context.Context, arg SwapBookingUnitParams) error {
	_, err := q.db.Exec(ctx, swapBookingUnit, arg.UnitID, arg.ID)
	return err
}
