// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (id, owner_id, created_by, name, category, pricing_unit,
                       base_price, deposit_amount, late_fee_per_unit,
                       min_duration, max_duration, buffer_minutes,
                       requires_id_verification)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type CreateResourceParams struct {
	ID                     uuid.UUID
	OwnerID                uuid.UUID
	CreatedBy              *uuid.UUID
	Name                   string
	Category               *string
	PricingUnit            string
	BasePrice              int64
	DepositAmount          *int64
	LateFeePerUnit         *int64
	MinDuration            *int32
	MaxDuration            *int32
	BufferMinutes          int32
	RequiresIDVerification bool
}

// pricing_unit comes from the caller, but the caller is internal/catalog reading
// owners.business_type -- never a request body (BR-012, BR-017). status is not
// settable here: a resource is born active.
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Name,
		arg.Category,
		arg.PricingUnit,
		arg.BasePrice,
		arg.DepositAmount,
		arg.LateFeePerUnit,
		arg.MinDuration,
		arg.MaxDuration,
		arg.BufferMinutes,
		arg.RequiresIDVerification,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO resource_units (id, owner_id, created_by, resource_id, code, label,
                            meter_value, condition_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, resource_id, code, label, status, meter_value, condition_notes
`

type CreateUnitParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	CreatedBy      *uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	MeterValue     *int64
	ConditionNotes *string
}

type CreateUnitRow struct {
	ID             uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	Status         string
	MeterValue     *int64
	ConditionNotes *string
}

// code is the client's (plate, serial -- BR-011), unlike bookings.code which the
// server generates. status is not settable here: a unit is born active.
func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (CreateUnitRow, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.ID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.ResourceID,
		arg.Code,
		arg.Label,
		arg.MeterValue,
		arg.ConditionNotes,
	)
	var i CreateUnitRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Code,
		&i.Label,
		&i.Status,
		&i.MeterValue,
		&i.ConditionNotes,
	)
	return i, err
}

const getOwnerBusinessType = `-- name: GetOwnerBusinessType :one
SELECT business_type FROM owners WHERE id = $1
`

// owners has no RLS -- it IS the tenant -- so this one really does need a WHERE.
// BR-017: the preset picks the pricing unit for every resource in the rental,
// and the mapping lives as a constant in Go, not as a column here.
func (q *Queries) GetOwnerBusinessType(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerBusinessType, id)
	var business_type string
	err := row.Scan(&business_type)
	return business_type, err
}

const getResource = `-- name: GetResource :one
SELECT r.id, r.name, r.category, r.pricing_unit, r.base_price,
       r.deposit_amount, r.late_fee_per_unit, r.min_duration, r.max_duration,
       r.buffer_minutes, r.requires_id_verification, r.status,
       (SELECT count(*) FROM resource_units u
         WHERE u.resource_id = r.id
           AND u.status = 'active' AND u.deleted_at IS NULL) AS unit_count
  FROM resources r
 WHERE r.id = $1 AND r.deleted_at IS NULL
`

type GetResourceRow struct {
	ID                     uuid.UUID
	Name                   string
	Category               *string
	PricingUnit            string
	BasePrice              int64
	DepositAmount          *int64
	LateFeePerUnit         *int64
	MinDuration            *int32
	MaxDuration            *int32
	BufferMinutes          int32
	RequiresIDVerification bool
	Status                 string
	UnitCount              int64
}

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PricingUnit,
		&i.BasePrice,
		&i.DepositAmount,
		&i.LateFeePerUnit,
		&i.MinDuration,
		&i.MaxDuration,
		&i.BufferMinutes,
		&i.RequiresIDVerification,
		&i.Status,
		&i.UnitCount,
	)
	return i, err
}

const listResources = `-- name: ListResources :many

SELECT r.id, r.name, r.category, r.pricing_unit, r.base_price,
       r.deposit_amount, r.late_fee_per_unit, r.min_duration, r.max_duration,
       r.buffer_minutes, r.requires_id_verification, r.status,
       (SELECT count(*) FROM resource_units u
         WHERE u.resource_id = r.id
           AND u.status = 'active' AND u.deleted_at IS NULL) AS unit_count
  FROM resources r
 WHERE r.deleted_at IS NULL
 ORDER BY r.name
`

type ListResourcesRow struct {
	ID                     uuid.UUID
	Name                   string
	Category               *string
	PricingUnit            string
	BasePrice              int64
	DepositAmount          *int64
	LateFeePerUnit         *int64
	MinDuration            *int32
	MaxDuration            *int32
	BufferMinutes          int32
	RequiresIDVerification bool
	Status                 string
	UnitCount              int64
}

// Catalogue: resources and their physical units.  (S1-014 .. S1-017)
//
// Every query here runs inside InOwnerTx, so RLS has already scoped both tables
// to one rental. That is what makes the id-taking queries return zero rows for
// another owner's id -- no ownership check in Go, and none wanted (BR-001).
//
// owner_id appears only as an INSERT column value, where the policy's WITH CHECK
// half validates it. It is never a WHERE clause.
// unit_count is active units only: a resource with none never appears in
// availability search however healthy its own status looks (BR-010), and the
// catalogue screen has to be able to say so.
func (q *Queries) ListResources(ctx context.Context) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourcesRow
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.PricingUnit,
			&i.BasePrice,
			&i.DepositAmount,
			&i.LateFeePerUnit,
			&i.MinDuration,
			&i.MaxDuration,
			&i.BufferMinutes,
			&i.RequiresIDVerification,
			&i.Status,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, resource_id, code, label, status, meter_value, condition_notes
  FROM resource_units
 WHERE resource_id = $1 AND deleted_at IS NULL
 ORDER BY code
`

type ListUnitsRow struct {
	ID             uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	Status         string
	MeterValue     *int64
	ConditionNotes *string
}

func (q *Queries) ListUnits(ctx context.Context, resourceID uuid.UUID) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitsRow
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Code,
			&i.Label,
			&i.Status,
			&i.MeterValue,
			&i.ConditionNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourceExists = `-- name: ResourceExists :one
SELECT EXISTS (SELECT 1 FROM resources WHERE id = $1)
`

// Distinguishes "already deleted" (204, idempotent) from "not in this rental"
// (404). SoftDeleteResource alone cannot: both return zero rows.
func (q *Queries) ResourceExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, resourceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteResource = `-- name: SoftDeleteResource :execrows
UPDATE resources SET deleted_at = now(), updated_at = now()
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteResource(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteResource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUnit = `-- name: SoftDeleteUnit :execrows
UPDATE resource_units SET deleted_at = now(), updated_at = now()
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUnit(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUnitsOfResource = `-- name: SoftDeleteUnitsOfResource :execrows
UPDATE resource_units SET deleted_at = now(), updated_at = now()
 WHERE resource_id = $1 AND deleted_at IS NULL
`

// Runs in the same transaction as SoftDeleteResource. Units left behind would
// belong to a kind nothing can see, and -- worse -- would keep holding their
// codes, because the unique index only excludes deleted rows (BR-011). A plate
// that moved to another car has to be usable on that car.
func (q *Queries) SoftDeleteUnitsOfResource(ctx context.Context, resourceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUnitsOfResource, resourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unitExists = `-- name: UnitExists :one
SELECT EXISTS (SELECT 1 FROM resource_units WHERE id = $1)
`

func (q *Queries) UnitExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, unitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET
    name         = COALESCE($1,     name),
    category     = COALESCE($2, category),
    base_price   = COALESCE($3::bigint, base_price),
    status       = COALESCE($4,   status),
    buffer_minutes = COALESCE($5::int, buffer_minutes),
    requires_id_verification =
        COALESCE($6::boolean, requires_id_verification),

    deposit_amount = CASE WHEN $7::boolean
                          THEN $8::bigint
                          ELSE deposit_amount END,
    late_fee_per_unit = CASE WHEN $9::boolean
                             THEN $10::bigint
                             ELSE late_fee_per_unit END,
    min_duration = CASE WHEN $11::boolean
                        THEN $12::int
                        ELSE min_duration END,
    max_duration = CASE WHEN $13::boolean
                        THEN $14::int
                        ELSE max_duration END,

    updated_at = now()
 WHERE id = $15 AND deleted_at IS NULL
RETURNING id
`

type UpdateResourceParams struct {
	Name                   *string
	Category               *string
	BasePrice              *int64
	Status                 *string
	BufferMinutes          *int32
	RequiresIDVerification *bool
	SetDepositAmount       bool
	DepositAmount          *int64
	SetLateFeePerUnit      bool
	LateFeePerUnit         *int64
	SetMinDuration         bool
	MinDuration            *int32
	SetMaxDuration         bool
	MaxDuration            *int32
	ID                     uuid.UUID
}

// Two idioms in one statement, and the difference is the whole of BR-016.
//
// COALESCE for the fields where absent means "leave it": there is no way to
// clear them, so nil can stand in for "not mentioned".
//
// CASE for the four nominals, where absent and null are DIFFERENT instructions:
// absent leaves the value, null revokes it (04-api-spec.md section 3.2).
// COALESCE cannot express that -- it reads both as "leave it" -- so each one
// carries a companion boolean saying whether the key was there at all.
func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Name,
		arg.Category,
		arg.BasePrice,
		arg.Status,
		arg.BufferMinutes,
		arg.RequiresIDVerification,
		arg.SetDepositAmount,
		arg.DepositAmount,
		arg.SetLateFeePerUnit,
		arg.LateFeePerUnit,
		arg.SetMinDuration,
		arg.MinDuration,
		arg.SetMaxDuration,
		arg.MaxDuration,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE resource_units SET
    code            = COALESCE($1,   code),
    label           = COALESCE($2,  label),
    status          = COALESCE($3, status),
    meter_value     = COALESCE($4::bigint, meter_value),
    condition_notes = COALESCE($5, condition_notes),
    updated_at      = now()
 WHERE id = $6 AND deleted_at IS NULL
RETURNING id, resource_id, code, label, status, meter_value, condition_notes
`

type UpdateUnitParams struct {
	Code           *string
	Label          *string
	Status         *string
	MeterValue     *int64
	ConditionNotes *string
	ID             uuid.UUID
}

type UpdateUnitRow struct {
	ID             uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	Status         string
	MeterValue     *int64
	ConditionNotes *string
}

// No CASE pairs here: none of these four is a BR-016 nominal, so absent can
// safely mean "leave it" and there is nothing to revoke.
func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (UpdateUnitRow, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.Code,
		arg.Label,
		arg.Status,
		arg.MeterValue,
		arg.ConditionNotes,
		arg.ID,
	)
	var i UpdateUnitRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Code,
		&i.Label,
		&i.Status,
		&i.MeterValue,
		&i.ConditionNotes,
	)
	return i, err
}
