// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :exec

INSERT INTO customers (id, owner_id, created_by, name, phone, id_type,
                       id_number_enc, id_number_last4)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateCustomerParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	CreatedBy     *uuid.UUID
	Name          string
	Phone         string
	IDType        *string
	IDNumberEnc   []byte
	IDNumberLast4 *string
}

// Penyewa dan jejak audit.  (S1-020, S1-021)
//
// Every query runs inside InOwnerTx; RLS scopes the rows. owner_id appears only
// as an INSERT value.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.Exec(ctx, createCustomer,
		arg.ID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Name,
		arg.Phone,
		arg.IDType,
		arg.IDNumberEnc,
		arg.IDNumberLast4,
	)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, phone, id_type, id_number_last4, is_blacklisted,
       blacklist_reason, created_at
  FROM customers
 WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerRow struct {
	ID              uuid.UUID
	Name            string
	Phone           string
	IDType          *string
	IDNumberLast4   *string
	IsBlacklisted   bool
	BlacklistReason *string
	CreatedAt       time.Time
}

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.IDType,
		&i.IDNumberLast4,
		&i.IsBlacklisted,
		&i.BlacklistReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, owner_id, actor_user_id, action, entity, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	ActorUserID uuid.UUID
	Action      string
	Entity      string
	EntityID    uuid.UUID
	Metadata    []byte
}

// The only statement against audit_logs. There is no UPDATE or DELETE query,
// and 000012 revokes both from app_user so there cannot be one (BR-085).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OwnerID,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, phone, id_type, id_number_last4, is_blacklisted,
       blacklist_reason, created_at
  FROM customers
 WHERE deleted_at IS NULL
   AND ($1::text IS NULL
        OR name ILIKE '%' || $1::text || '%'
        OR phone ILIKE '%' || $1::text || '%')
   AND ($2::boolean IS NULL OR is_blacklisted = $2::boolean)
   AND ($3::uuid IS NULL OR id < $3::uuid)
 ORDER BY id DESC
 LIMIT $4
`

type ListCustomersParams struct {
	Q           *string
	Blacklisted *bool
	Cursor      *uuid.UUID
	Lim         int32
}

type ListCustomersRow struct {
	ID              uuid.UUID
	Name            string
	Phone           string
	IDType          *string
	IDNumberLast4   *string
	IsBlacklisted   bool
	BlacklistReason *string
	CreatedAt       time.Time
}

// Keyset on id: UUID v7 is creation order, so "newest first" and the cursor are
// the same column. q matches name or phone, case-insensitively -- the booking
// form searches while the operator types.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.Q,
		arg.Blacklisted,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.IDType,
			&i.IDNumberLast4,
			&i.IsBlacklisted,
			&i.BlacklistReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerBlacklist = `-- name: SetCustomerBlacklist :execrows
UPDATE customers SET
    is_blacklisted   = $1,
    blacklist_reason = $2,
    updated_at       = now()
 WHERE id = $3 AND deleted_at IS NULL
`

type SetCustomerBlacklistParams struct {
	IsBlacklisted   bool
	BlacklistReason *string
	ID              uuid.UUID
}

// One statement for both directions: customers_blacklist_has_reason makes the
// flag and the reason travel together, so unblocking passes NULL for both.
func (q *Queries) SetCustomerBlacklist(ctx context.Context, arg SetCustomerBlacklistParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerBlacklist, arg.IsBlacklisted, arg.BlacklistReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCustomer = `-- name: UpdateCustomer :execrows
UPDATE customers SET
    name            = COALESCE($1,  name),
    phone           = COALESCE($2, phone),
    id_type         = COALESCE($3, id_type),
    id_number_enc   = COALESCE($4::bytea, id_number_enc),
    id_number_last4 = COALESCE($5, id_number_last4),
    updated_at      = now()
 WHERE id = $6 AND deleted_at IS NULL
`

type UpdateCustomerParams struct {
	Name          *string
	Phone         *string
	IDType        *string
	IDNumberEnc   []byte
	IDNumberLast4 *string
	ID            uuid.UUID
}

// Blacklisting is not here on purpose: an operator may call this, and BR-028
// says an operator may not block anyone.
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomer,
		arg.Name,
		arg.Phone,
		arg.IDType,
		arg.IDNumberEnc,
		arg.IDNumberLast4,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
