// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handovers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const handoverExists = `-- name: HandoverExists :one
SELECT EXISTS (SELECT 1 FROM handovers WHERE id = $1)
`

func (q *Queries) HandoverExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, handoverExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHandover = `-- name: InsertHandover :exec

INSERT INTO handovers (id, owner_id, booking_id, direction, performed_by, meter_value,
                       checklist, condition_notes, late_fee_waived, waiver_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertHandoverParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	BookingID      uuid.UUID
	Direction      string
	PerformedBy    uuid.UUID
	MeterValue     *int64
	Checklist      []byte
	ConditionNotes *string
	LateFeeWaived  *int64
	WaiverReason   *string
}

// Bukti kondisi.  (S1-034 .. S1-036)
//
// INSERT and SELECT only. There is no UPDATE or DELETE query here and there
// cannot be one that works: 000014 revokes both from app_user (BR-037).
func (q *Queries) InsertHandover(ctx context.Context, arg InsertHandoverParams) error {
	_, err := q.db.Exec(ctx, insertHandover,
		arg.ID,
		arg.OwnerID,
		arg.BookingID,
		arg.Direction,
		arg.PerformedBy,
		arg.MeterValue,
		arg.Checklist,
		arg.ConditionNotes,
		arg.LateFeeWaived,
		arg.WaiverReason,
	)
	return err
}

const insertHandoverPhoto = `-- name: InsertHandoverPhoto :exec
INSERT INTO handover_photos (id, owner_id, handover_id, object_key) VALUES ($1, $2, $3, $4)
`

type InsertHandoverPhotoParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	HandoverID uuid.UUID
	ObjectKey  string
}

func (q *Queries) InsertHandoverPhoto(ctx context.Context, arg InsertHandoverPhotoParams) error {
	_, err := q.db.Exec(ctx, insertHandoverPhoto,
		arg.ID,
		arg.OwnerID,
		arg.HandoverID,
		arg.ObjectKey,
	)
	return err
}

const listHandoverPhotos = `-- name: ListHandoverPhotos :many
SELECT p.id, p.handover_id, p.object_key, p.captured_at
  FROM handover_photos p
  JOIN handovers h ON h.id = p.handover_id
 WHERE h.booking_id = $1
 ORDER BY p.captured_at, p.id
`

type ListHandoverPhotosRow struct {
	ID         uuid.UUID
	HandoverID uuid.UUID
	ObjectKey  string
	CapturedAt time.Time
}

func (q *Queries) ListHandoverPhotos(ctx context.Context, bookingID uuid.UUID) ([]ListHandoverPhotosRow, error) {
	rows, err := q.db.Query(ctx, listHandoverPhotos, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoverPhotosRow
	for rows.Next() {
		var i ListHandoverPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.HandoverID,
			&i.ObjectKey,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandovers = `-- name: ListHandovers :many
SELECT h.id, h.direction, u.name AS performed_by, h.performed_at, h.meter_value,
       h.checklist, h.condition_notes, h.late_fee_waived, h.waiver_reason
  FROM handovers h
  JOIN users u ON u.id = h.performed_by
 WHERE h.booking_id = $1
 ORDER BY h.performed_at
`

type ListHandoversRow struct {
	ID             uuid.UUID
	Direction      string
	PerformedBy    string
	PerformedAt    time.Time
	MeterValue     *int64
	Checklist      []byte
	ConditionNotes *string
	LateFeeWaived  *int64
	WaiverReason   *string
}

func (q *Queries) ListHandovers(ctx context.Context, bookingID uuid.UUID) ([]ListHandoversRow, error) {
	rows, err := q.db.Query(ctx, listHandovers, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoversRow
	for rows.Next() {
		var i ListHandoversRow
		if err := rows.Scan(
			&i.ID,
			&i.Direction,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.MeterValue,
			&i.Checklist,
			&i.ConditionNotes,
			&i.LateFeeWaived,
			&i.WaiverReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
