// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBookingInvoices = `-- name: CountBookingInvoices :one
SELECT count(*) FROM invoices WHERE booking_id = $1
`

// The next invoice number of a booking is this + 1. Safe because every caller
// holds the booking row lock (LockBooking*), and the unique index is the
// backstop if one ever does not.
func (q *Queries) CountBookingInvoices(ctx context.Context, bookingID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingInvoices, bookingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT i.id, i.booking_id, i.number, i.status, i.due_at, i.paid_at, i.created_at,
       COALESCE((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id), 0)::bigint AS total
  FROM invoices i
 WHERE i.id = $1 AND i.deleted_at IS NULL
`

type GetInvoiceRow struct {
	ID        uuid.UUID
	BookingID *uuid.UUID
	Number    string
	Status    string
	DueAt     time.Time
	PaidAt    *time.Time
	CreatedAt time.Time
	Total     int64
}

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Number,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Total,
	)
	return i, err
}

const getPaymentDueHours = `-- name: GetPaymentDueHours :one
SELECT payment_due_hours FROM owners WHERE id = $1
`

func (q *Queries) GetPaymentDueHours(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPaymentDueHours, id)
	var payment_due_hours int32
	err := row.Scan(&payment_due_hours)
	return payment_due_hours, err
}

const insertInvoice = `-- name: InsertInvoice :exec

INSERT INTO invoices (id, owner_id, booking_id, customer_id, number, due_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInvoiceParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	BookingID  *uuid.UUID
	CustomerID *uuid.UUID
	Number     string
	DueAt      time.Time
	CreatedBy  *uuid.UUID
}

// Invoice.  (S1-041)
//
// No total column anywhere: every read sums the lines (BR-055).
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.ID,
		arg.OwnerID,
		arg.BookingID,
		arg.CustomerID,
		arg.Number,
		arg.DueAt,
		arg.CreatedBy,
	)
	return err
}

const insertInvoiceLine = `-- name: InsertInvoiceLine :exec
INSERT INTO invoice_lines (id, owner_id, invoice_id, kind, description, amount,
                           handover_photo_id, waiver_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertInvoiceLineParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	InvoiceID       uuid.UUID
	Kind            string
	Description     string
	Amount          int64
	HandoverPhotoID *uuid.UUID
	WaiverReason    *string
}

func (q *Queries) InsertInvoiceLine(ctx context.Context, arg InsertInvoiceLineParams) error {
	_, err := q.db.Exec(ctx, insertInvoiceLine,
		arg.ID,
		arg.OwnerID,
		arg.InvoiceID,
		arg.Kind,
		arg.Description,
		arg.Amount,
		arg.HandoverPhotoID,
		arg.WaiverReason,
	)
	return err
}

const listBookingInvoices = `-- name: ListBookingInvoices :many
SELECT i.id, i.booking_id, i.number, i.status, i.due_at, i.paid_at, i.created_at,
       COALESCE((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id), 0)::bigint AS total
  FROM invoices i
 WHERE i.booking_id = $1 AND i.deleted_at IS NULL
 ORDER BY i.created_at, i.number
`

type ListBookingInvoicesRow struct {
	ID        uuid.UUID
	BookingID *uuid.UUID
	Number    string
	Status    string
	DueAt     time.Time
	PaidAt    *time.Time
	CreatedAt time.Time
	Total     int64
}

func (q *Queries) ListBookingInvoices(ctx context.Context, bookingID *uuid.UUID) ([]ListBookingInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listBookingInvoices, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingInvoicesRow
	for rows.Next() {
		var i ListBookingInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Number,
			&i.Status,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
SELECT id, invoice_id, kind, description, amount, handover_photo_id, waiver_reason
  FROM invoice_lines
 WHERE invoice_id = ANY($1::uuid[])
 ORDER BY created_at, id
`

type ListInvoiceLinesRow struct {
	ID              uuid.UUID
	InvoiceID       uuid.UUID
	Kind            string
	Description     string
	Amount          int64
	HandoverPhotoID *uuid.UUID
	WaiverReason    *string
}

func (q *Queries) ListInvoiceLines(ctx context.Context, invoiceIds []uuid.UUID) ([]ListInvoiceLinesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, invoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoiceLinesRow
	for rows.Next() {
		var i ListInvoiceLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Kind,
			&i.Description,
			&i.Amount,
			&i.HandoverPhotoID,
			&i.WaiverReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rentInvoiceState = `-- name: RentInvoiceState :one
SELECT EXISTS (SELECT 1 FROM invoices i
                 JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind = 'rent'
                WHERE i.booking_id = $1 AND i.deleted_at IS NULL)::boolean AS has_rent,
       EXISTS (SELECT 1 FROM invoices i
                 JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind = 'rent'
                WHERE i.booking_id = $1 AND i.status = 'paid' AND i.deleted_at IS NULL)::boolean AS paid
`

type RentInvoiceStateRow struct {
	HasRent bool
	Paid    bool
}

// BR-038 reads "the rent invoice is paid": the invoice carrying the rent line.
// has_rent is false for a free booking (base_price 0), which has nothing to
// pay and so nothing to block on.
func (q *Queries) RentInvoiceState(ctx context.Context, bookingID *uuid.UUID) (RentInvoiceStateRow, error) {
	row := q.db.QueryRow(ctx, rentInvoiceState, bookingID)
	var i RentInvoiceStateRow
	err := row.Scan(&i.HasRent, &i.Paid)
	return i, err
}
