// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Owner struct {
	ID                         uuid.UUID
	Slug                       *string
	Name                       string
	Status                     string
	RequirePaymentBeforePickup bool
	DraftExpiryHours           int32
	NotifyPickupReminder       bool
	NotifyReturnReminder       bool
	NotifyOverdueReminder      bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	BookingCodePrefix          string
	PaymentDueHours            int32
	NoShowToleranceHours       int32
	BusinessType               string
}

type RefreshToken struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type User struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Email           string
	PasswordHash    *string
	Name            string
	Phone           *string
	Role            string
	Status          string
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmailVerifiedAt *time.Time
}
