// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Name            string
	KeyPrefix       string
	KeyHash         string
	RateLimitPerMin int32
	LastUsedAt      *time.Time
	RevokedAt       *time.Time
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
}

type AuditLog struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	ActorUserID uuid.UUID
	Action      string
	Entity      string
	EntityID    uuid.UUID
	Metadata    []byte
	CreatedAt   time.Time
}

type Booking struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	Code                string
	CustomerID          uuid.UUID
	ResourceID          uuid.UUID
	ResourceUnitID      uuid.UUID
	StartAt             time.Time
	EndAt               time.Time
	EndAtWithBuffer     time.Time
	Status              string
	Source              string
	UnitPrice           int64
	PricingUnit         string
	BufferMinutes       int32
	DurationQty         int32
	Subtotal            int64
	DepositAmount       *int64
	LateFeePerUnit      *int64
	DepositWaivedAt     *time.Time
	DepositWaivedBy     *uuid.UUID
	DepositWaiverReason *string
	ActualReturnAt      *time.Time
	DepositDeducted     int64
	DepositRefunded     int64
	DepositNote         *string
	ExpiresAt           *time.Time
	CancelledReason     *string
	CreatedBy           *uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
	DepositSettledAt    *time.Time
}

type BookingCounter struct {
	OwnerID    uuid.UUID
	LastNumber int64
}

type Customer struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Name            string
	Phone           string
	IDType          *string
	IDNumberEnc     []byte
	IDNumberLast4   *string
	IDPhotoKey      *string
	IsBlacklisted   bool
	BlacklistReason *string
	IDPurgeAfter    *time.Time
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type Handover struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	BookingID      uuid.UUID
	Direction      string
	PerformedBy    uuid.UUID
	PerformedAt    time.Time
	MeterValue     *int64
	Checklist      []byte
	ConditionNotes *string
	LateFeeWaived  *int64
	WaiverReason   *string
	CreatedAt      time.Time
}

type HandoverPhoto struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	HandoverID uuid.UUID
	ObjectKey  string
	CapturedAt time.Time
}

type Invoice struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Kind           string
	BookingID      *uuid.UUID
	SubscriptionID *uuid.UUID
	CustomerID     *uuid.UUID
	Number         string
	Status         string
	DueAt          time.Time
	PaidAt         *time.Time
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type InvoiceLine struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	InvoiceID       uuid.UUID
	Kind            string
	Description     string
	Amount          int64
	HandoverPhotoID *uuid.UUID
	WaiverReason    *string
	CreatedAt       time.Time
}

type Owner struct {
	ID                         uuid.UUID
	Slug                       *string
	Name                       string
	Status                     string
	RequirePaymentBeforePickup bool
	DraftExpiryHours           int32
	NotifyPickupReminder       bool
	NotifyReturnReminder       bool
	NotifyOverdueReminder      bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	BookingCodePrefix          string
	PaymentDueHours            int32
	NoShowToleranceHours       int32
	BusinessType               string
	Whatsapp                   *string
	Address                    *string
	OperatingHours             *string
	BankName                   *string
	BankAccountNumber          *string
	BankAccountHolder          *string
	AllowedOrigins             []string
}

type Payment struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	InvoiceID  uuid.UUID
	Method     string
	Amount     int64
	Status     string
	PaidAt     time.Time
	ApprovedBy uuid.UUID
	CreatedAt  time.Time
}

type PaymentProof struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	InvoiceID    uuid.UUID
	ObjectKey    string
	ContentType  string
	MatchStatus  *string
	AiAmount     *int64
	AiPaidAt     *time.Time
	ReviewStatus string
	ReviewedBy   *uuid.UUID
	ReviewedAt   *time.Time
	RejectReason *string
	PaymentID    *uuid.UUID
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
}

type RefreshToken struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Resource struct {
	ID                     uuid.UUID
	OwnerID                uuid.UUID
	Name                   string
	Category               *string
	Images                 []string
	PricingUnit            string
	BasePrice              int64
	DepositAmount          *int64
	LateFeePerUnit         *int64
	MinDuration            *int32
	MaxDuration            *int32
	BufferMinutes          int32
	RequiresIDVerification bool
	Status                 string
	CreatedBy              *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              *time.Time
	Description            *string
	TermsExcludes          *string
	TermsRequirements      *string
	TermsCancellation      *string
}

type ResourceUnit struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	Status         string
	MeterValue     *int64
	ConditionNotes *string
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type User struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Email           string
	PasswordHash    *string
	Name            string
	Phone           *string
	Role            string
	Status          string
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmailVerifiedAt *time.Time
}

type VehicleSpec struct {
	ResourceID   uuid.UUID
	OwnerID      uuid.UUID
	VehicleType  string
	Transmission string
	Seats        *int32
	Fuel         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VehicleUnitDetail struct {
	ResourceUnitID         uuid.UUID
	OwnerID                uuid.UUID
	Year                   int32
	Color                  *string
	TaxDueOn               *time.Time
	RegistrationValidUntil *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}
