// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Owner struct {
	ID                         uuid.UUID
	Slug                       *string
	Name                       string
	Status                     string
	RequirePaymentBeforePickup bool
	DraftExpiryHours           int32
	NotifyPickupReminder       bool
	NotifyReturnReminder       bool
	NotifyOverdueReminder      bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	BookingCodePrefix          string
	PaymentDueHours            int32
	NoShowToleranceHours       int32
	BusinessType               string
	Whatsapp                   *string
	Address                    *string
	OperatingHours             *string
}

type RefreshToken struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Resource struct {
	ID                     uuid.UUID
	OwnerID                uuid.UUID
	Name                   string
	Category               *string
	Images                 []string
	PricingUnit            string
	BasePrice              int64
	DepositAmount          *int64
	LateFeePerUnit         *int64
	MinDuration            *int32
	MaxDuration            *int32
	BufferMinutes          int32
	RequiresIDVerification bool
	Status                 string
	CreatedBy              *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              *time.Time
	Description            *string
	TermsExcludes          *string
	TermsRequirements      *string
	TermsCancellation      *string
}

type ResourceUnit struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	ResourceID     uuid.UUID
	Code           string
	Label          *string
	Status         string
	MeterValue     *int64
	ConditionNotes *string
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type User struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Email           string
	PasswordHash    *string
	Name            string
	Phone           *string
	Role            string
	Status          string
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmailVerifiedAt *time.Time
}

type VehicleSpec struct {
	ResourceID   uuid.UUID
	OwnerID      uuid.UUID
	VehicleType  string
	Transmission string
	Seats        *int32
	Fuel         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VehicleUnitDetail struct {
	ResourceUnitID         uuid.UUID
	OwnerID                uuid.UUID
	Year                   int32
	Color                  *string
	TaxDueOn               *time.Time
	RegistrationValidUntil *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}
