// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approveProof = `-- name: ApproveProof :exec
UPDATE payment_proofs SET review_status = 'approved', reviewed_by = $2, reviewed_at = now(), payment_id = $3
 WHERE id = $1
`

type ApproveProofParams struct {
	ID         uuid.UUID
	ReviewedBy *uuid.UUID
	PaymentID  *uuid.UUID
}

func (q *Queries) ApproveProof(ctx context.Context, arg ApproveProofParams) error {
	_, err := q.db.Exec(ctx, approveProof, arg.ID, arg.ReviewedBy, arg.PaymentID)
	return err
}

const getProof = `-- name: GetProof :one
SELECT p.id, p.invoice_id, p.object_key, p.content_type, p.review_status, p.match_status,
       p.ai_amount, p.ai_paid_at, u.name AS reviewed_by_name, p.reviewed_at, p.reject_reason, p.created_at
  FROM payment_proofs p
  LEFT JOIN users u ON u.id = p.reviewed_by
 WHERE p.id = $1
`

type GetProofRow struct {
	ID             uuid.UUID
	InvoiceID      uuid.UUID
	ObjectKey      string
	ContentType    string
	ReviewStatus   string
	MatchStatus    *string
	AiAmount       *int64
	AiPaidAt       *time.Time
	ReviewedByName *string
	ReviewedAt     *time.Time
	RejectReason   *string
	CreatedAt      time.Time
}

func (q *Queries) GetProof(ctx context.Context, id uuid.UUID) (GetProofRow, error) {
	row := q.db.QueryRow(ctx, getProof, id)
	var i GetProofRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ObjectKey,
		&i.ContentType,
		&i.ReviewStatus,
		&i.MatchStatus,
		&i.AiAmount,
		&i.AiPaidAt,
		&i.ReviewedByName,
		&i.ReviewedAt,
		&i.RejectReason,
		&i.CreatedAt,
	)
	return i, err
}

const getProofForScan = `-- name: GetProofForScan :one
SELECT object_key, content_type, review_status, match_status FROM payment_proofs WHERE id = $1
`

type GetProofForScanRow struct {
	ObjectKey    string
	ContentType  string
	ReviewStatus string
	MatchStatus  *string
}

func (q *Queries) GetProofForScan(ctx context.Context, id uuid.UUID) (GetProofForScanRow, error) {
	row := q.db.QueryRow(ctx, getProofForScan, id)
	var i GetProofForScanRow
	err := row.Scan(
		&i.ObjectKey,
		&i.ContentType,
		&i.ReviewStatus,
		&i.MatchStatus,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (id, owner_id, invoice_id, method, amount, status, paid_at, approved_by)
VALUES ($1, $2, $3, $4, $5, 'success', $6, $7)
`

type InsertPaymentParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	InvoiceID  uuid.UUID
	Method     string
	Amount     int64
	PaidAt     time.Time
	ApprovedBy uuid.UUID
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.OwnerID,
		arg.InvoiceID,
		arg.Method,
		arg.Amount,
		arg.PaidAt,
		arg.ApprovedBy,
	)
	return err
}

const insertProof = `-- name: InsertProof :exec
INSERT INTO payment_proofs (id, owner_id, invoice_id, object_key, content_type, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProofParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	InvoiceID   uuid.UUID
	ObjectKey   string
	ContentType string
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertProof(ctx context.Context, arg InsertProofParams) error {
	_, err := q.db.Exec(ctx, insertProof,
		arg.ID,
		arg.OwnerID,
		arg.InvoiceID,
		arg.ObjectKey,
		arg.ContentType,
		arg.CreatedBy,
	)
	return err
}

const listOwnerInvoices = `-- name: ListOwnerInvoices :many
SELECT i.id, i.booking_id, i.number, i.status, i.due_at, i.paid_at, i.created_at,
       COALESCE((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id), 0)::bigint AS total
  FROM invoices i
 WHERE i.deleted_at IS NULL
   AND ($1::text IS NULL OR i.status = $1::text)
   AND ($2::timestamptz IS NULL
        OR (i.created_at, i.id) < ($2::timestamptz, $3::uuid))
 ORDER BY i.created_at DESC, i.id DESC
 LIMIT $4
`

type ListOwnerInvoicesParams struct {
	Status   *string
	CursorAt *time.Time
	CursorID *uuid.UUID
	Lim      int32
}

type ListOwnerInvoicesRow struct {
	ID        uuid.UUID
	BookingID *uuid.UUID
	Number    string
	Status    string
	DueAt     time.Time
	PaidAt    *time.Time
	CreatedAt time.Time
	Total     int64
}

// The owner's full list (S1-047), newest first, keyset on (created_at, id).
func (q *Queries) ListOwnerInvoices(ctx context.Context, arg ListOwnerInvoicesParams) ([]ListOwnerInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listOwnerInvoices,
		arg.Status,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerInvoicesRow
	for rows.Next() {
		var i ListOwnerInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Number,
			&i.Status,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProofs = `-- name: ListProofs :many
SELECT p.id, p.invoice_id, p.object_key, p.content_type, p.review_status, p.match_status,
       p.ai_amount, p.ai_paid_at, u.name AS reviewed_by_name, p.reviewed_at, p.reject_reason, p.created_at
  FROM payment_proofs p
  LEFT JOIN users u ON u.id = p.reviewed_by
 WHERE p.invoice_id = $1
 ORDER BY p.created_at DESC
`

type ListProofsRow struct {
	ID             uuid.UUID
	InvoiceID      uuid.UUID
	ObjectKey      string
	ContentType    string
	ReviewStatus   string
	MatchStatus    *string
	AiAmount       *int64
	AiPaidAt       *time.Time
	ReviewedByName *string
	ReviewedAt     *time.Time
	RejectReason   *string
	CreatedAt      time.Time
}

func (q *Queries) ListProofs(ctx context.Context, invoiceID uuid.UUID) ([]ListProofsRow, error) {
	rows, err := q.db.Query(ctx, listProofs, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProofsRow
	for rows.Next() {
		var i ListProofsRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ObjectKey,
			&i.ContentType,
			&i.ReviewStatus,
			&i.MatchStatus,
			&i.AiAmount,
			&i.AiPaidAt,
			&i.ReviewedByName,
			&i.ReviewedAt,
			&i.RejectReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvoice = `-- name: LockInvoice :one

SELECT i.id, i.booking_id, i.status,
       COALESCE((SELECT sum(l.amount) FROM invoice_lines l WHERE l.invoice_id = i.id), 0)::bigint AS total
  FROM invoices i
 WHERE i.id = $1 AND i.deleted_at IS NULL
   FOR UPDATE OF i
`

type LockInvoiceRow struct {
	ID        uuid.UUID
	BookingID *uuid.UUID
	Status    string
	Total     int64
}

// Pembayaran dan bukti transfer.  (S1-044, S1-046)
// The row lock serialises two payments on one invoice; the unique index
// payments_one_success_per_invoice is the backstop if anything ever skips it.
func (q *Queries) LockInvoice(ctx context.Context, id uuid.UUID) (LockInvoiceRow, error) {
	row := q.db.QueryRow(ctx, lockInvoice, id)
	var i LockInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Status,
		&i.Total,
	)
	return i, err
}

const lockProof = `-- name: LockProof :one
SELECT id, invoice_id, review_status FROM payment_proofs WHERE id = $1 FOR UPDATE
`

type LockProofRow struct {
	ID           uuid.UUID
	InvoiceID    uuid.UUID
	ReviewStatus string
}

func (q *Queries) LockProof(ctx context.Context, id uuid.UUID) (LockProofRow, error) {
	row := q.db.QueryRow(ctx, lockProof, id)
	var i LockProofRow
	err := row.Scan(&i.ID, &i.InvoiceID, &i.ReviewStatus)
	return i, err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = $2, updated_at = now() WHERE id = $1
`

type MarkInvoicePaidParams struct {
	ID     uuid.UUID
	PaidAt *time.Time
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) error {
	_, err := q.db.Exec(ctx, markInvoicePaid, arg.ID, arg.PaidAt)
	return err
}

const rejectProof = `-- name: RejectProof :exec
UPDATE payment_proofs SET review_status = 'rejected', reviewed_by = $2, reviewed_at = now(), reject_reason = $3
 WHERE id = $1
`

type RejectProofParams struct {
	ID           uuid.UUID
	ReviewedBy   *uuid.UUID
	RejectReason *string
}

func (q *Queries) RejectProof(ctx context.Context, arg RejectProofParams) error {
	_, err := q.db.Exec(ctx, rejectProof, arg.ID, arg.ReviewedBy, arg.RejectReason)
	return err
}

const setProofReading = `-- name: SetProofReading :execrows
UPDATE payment_proofs SET match_status = $2, ai_amount = $3, ai_paid_at = $4
 WHERE id = $1 AND match_status IS NULL AND review_status = 'pending'
`

type SetProofReadingParams struct {
	ID          uuid.UUID
	MatchStatus *string
	AiAmount    *int64
	AiPaidAt    *time.Time
}

// Only on an unread, undecided proof: a second delivery of the same job (at-
// least-once, BR-091) or a human who already decided both win over the reader.
func (q *Queries) SetProofReading(ctx context.Context, arg SetProofReadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProofReading,
		arg.ID,
		arg.MatchStatus,
		arg.AiAmount,
		arg.AiPaidAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
