// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE users SET
    password_hash     = $2,
    status            = 'active',
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at        = now()
 WHERE id = $1 AND status = 'invited'
`

type AcceptInvitationParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

// The three things an invitation acceptance sets, in one statement so none can
// land without the others. email_verified_at is included because accepting a
// link that only arrived by email IS the proof a verification mail would ask
// for -- asking again is asking twice (BR-004, BR-006).
func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOwner = `-- name: CreateOwner :exec
INSERT INTO owners (id, name, business_type) VALUES ($1, $2, $3)
`

type CreateOwnerParams struct {
	ID           uuid.UUID
	Name         string
	BusinessType string
}

// The only statement in the system that creates a business (BR-005). slug is
// absent on purpose: it is optional, paid, and filled in later from
// PATCH /settings, and asking for it at registration is one more place to stop.
func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) error {
	_, err := q.db.Exec(ctx, createOwner, arg.ID, arg.Name, arg.BusinessType)
	return err
}

const createOwnerUser = `-- name: CreateOwnerUser :exec
INSERT INTO users (id, owner_id, email, password_hash, name, role, status)
VALUES ($1, $2, $3, $4, $5, 'owner', 'active')
`

type CreateOwnerUserParams struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	Email        string
	PasswordHash *string
	Name         string
}

// Runs in the same transaction as CreateOwner. A business without an owner is
// a row nobody can ever log into, so the two are one write or neither is.
func (q *Queries) CreateOwnerUser(ctx context.Context, arg CreateOwnerUserParams) error {
	_, err := q.db.Exec(ctx, createOwnerUser,
		arg.ID,
		arg.OwnerID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	return err
}

const getOwnerName = `-- name: GetOwnerName :one
SELECT name FROM owners WHERE id = $1
`

// For the invitation mail. owners has no RLS (it IS the tenant), so the WHERE
// clause is the isolation -- and the id comes from the owner context.
func (q *Queries) GetOwnerName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email, name, email_verified_at FROM users WHERE id = $1
`

type GetUserEmailRow struct {
	Email           string
	Name            string
	EmailVerifiedAt *time.Time
}

func (q *Queries) GetUserEmail(ctx context.Context, id uuid.UUID) (GetUserEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var i GetUserEmailRow
	err := row.Scan(&i.Email, &i.Name, &i.EmailVerifiedAt)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users SET email_verified_at = now(), updated_at = now()
 WHERE id = $1 AND email_verified_at IS NULL
`

// Idempotent by the WHERE clause: verifying twice is still verified, and the
// second call must not move the timestamp.
func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
