// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const absorbedCharges = `-- name: AbsorbedCharges :many
SELECT b.id AS booking_id, b.deposit_deducted, l.kind, l.amount
  FROM bookings b
  JOIN invoices i      ON i.booking_id = b.id AND i.status = 'cancelled' AND i.deleted_at IS NULL
  JOIN invoice_lines l ON l.invoice_id = i.id AND l.kind IN ('late_fee', 'damage')
 WHERE b.deposit_settled_at >= $1::timestamptz
   AND b.deposit_settled_at < $2::timestamptz
   AND b.deposit_deducted > 0 AND b.deleted_at IS NULL
 ORDER BY b.id, l.created_at, l.id
`

type AbsorbedChargesParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type AbsorbedChargesRow struct {
	BookingID       uuid.UUID
	DepositDeducted int64
	Kind            string
	Amount          int64
}

// Charges a deposit absorbed at settlement (M4): the late_fee and damage lines
// of a settled booking's cancelled invoices, in the order settle consumed
// them. A returned booking is never cancelled, so its cancelled invoices are
// exactly the absorbed ones.
func (q *Queries) AbsorbedCharges(ctx context.Context, arg AbsorbedChargesParams) ([]AbsorbedChargesRow, error) {
	rows, err := q.db.Query(ctx, absorbedCharges, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsorbedChargesRow
	for rows.Next() {
		var i AbsorbedChargesRow
		if err := rows.Scan(
			&i.BookingID,
			&i.DepositDeducted,
			&i.Kind,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBookings = `-- name: DashboardBookings :many
SELECT b.id, b.code, b.status, b.start_at, b.end_at,
       c.name AS customer_name, r.name AS resource_name,
       u.id AS unit_id, u.code AS unit_code, u.label AS unit_label
  FROM bookings b
  JOIN customers c      ON c.id = b.customer_id
  JOIN resources r      ON r.id = b.resource_id
  JOIN resource_units u ON u.id = b.resource_unit_id
 WHERE b.deleted_at IS NULL AND b.status = $1::text
   AND ($2::timestamptz IS NULL OR b.start_at >= $2::timestamptz)
   AND ($3::timestamptz IS NULL OR b.start_at < $3::timestamptz)
   AND ($4::timestamptz IS NULL OR b.end_at >= $4::timestamptz)
   AND ($5::timestamptz IS NULL OR b.end_at < $5::timestamptz)
   AND (NOT $6::boolean
        OR (b.deposit_amount IS NOT NULL AND b.deposit_waived_at IS NULL AND b.deposit_settled_at IS NULL))
 ORDER BY b.start_at
 LIMIT 50
`

type DashboardBookingsParams struct {
	Status           string
	StartFrom        *time.Time
	StartTo          *time.Time
	EndFrom          *time.Time
	EndTo            *time.Time
	UnsettledDeposit bool
}

type DashboardBookingsRow struct {
	ID           uuid.UUID
	Code         string
	Status       string
	StartAt      time.Time
	EndAt        time.Time
	CustomerName string
	ResourceName string
	UnitID       uuid.UUID
	UnitCode     string
	UnitLabel    *string
}

// One query for the four dashboard lists; the caller sets the conditions.
func (q *Queries) DashboardBookings(ctx context.Context, arg DashboardBookingsParams) ([]DashboardBookingsRow, error) {
	rows, err := q.db.Query(ctx, dashboardBookings,
		arg.Status,
		arg.StartFrom,
		arg.StartTo,
		arg.EndFrom,
		arg.EndTo,
		arg.UnsettledDeposit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBookingsRow
	for rows.Next() {
		var i DashboardBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CustomerName,
			&i.ResourceName,
			&i.UnitID,
			&i.UnitCode,
			&i.UnitLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const depositBalance = `-- name: DepositBalance :one
SELECT COALESCE(sum(l.amount), 0)::bigint
  FROM invoice_lines l
  JOIN invoices i ON i.id = l.invoice_id AND i.status = 'paid' AND i.deleted_at IS NULL
  JOIN bookings b ON b.id = i.booking_id
 WHERE l.kind = 'deposit' AND b.deposit_settled_at IS NULL AND b.deposit_waived_at IS NULL
   AND b.deleted_at IS NULL
`

// Held right now: deposits paid, neither settled nor waived (BR-050).
func (q *Queries) DepositBalance(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, depositBalance)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const depositsReturned = `-- name: DepositsReturned :one
SELECT COALESCE(sum(deposit_refunded), 0)::bigint
  FROM bookings
 WHERE deposit_settled_at >= $1::timestamptz
   AND deposit_settled_at < $2::timestamptz AND deleted_at IS NULL
`

type DepositsReturnedParams struct {
	FromAt time.Time
	ToAt   time.Time
}

func (q *Queries) DepositsReturned(ctx context.Context, arg DepositsReturnedParams) (int64, error) {
	row := q.db.QueryRow(ctx, depositsReturned, arg.FromAt, arg.ToAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const idleUnits = `-- name: IdleUnits :many
SELECT u.id, u.code, u.label, r.name AS resource_name,
       (max(COALESCE(b.actual_return_at, b.end_at)) IS NOT NULL)::boolean AS ever_rented,
       COALESCE(max(COALESCE(b.actual_return_at, b.end_at)), u.created_at)::timestamptz AS idle_since
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id AND r.deleted_at IS NULL
  LEFT JOIN bookings b ON b.resource_unit_id = u.id AND b.deleted_at IS NULL
        AND b.status IN ('picked_up', 'returned', 'completed')
 WHERE u.status = 'active' AND u.deleted_at IS NULL
 GROUP BY u.id, u.code, u.label, r.name, u.created_at
HAVING COALESCE(max(COALESCE(b.actual_return_at, b.end_at)), u.created_at) < $1::timestamptz
   -- COALESCE: bool_or over a unit with no bookings is NULL, and NOT NULL
   -- would quietly drop every never-rented unit from the list.
   AND NOT COALESCE(bool_or(b.status = 'picked_up'), false)
 ORDER BY idle_since, u.code
`

type IdleUnitsRow struct {
	ID           uuid.UUID
	Code         string
	Label        *string
	ResourceName string
	EverRented   bool
	IdleSince    time.Time
}

// Active units whose last rental ended before the cutoff -- or that were never
// rented and have existed since before it.
func (q *Queries) IdleUnits(ctx context.Context, cutoff time.Time) ([]IdleUnitsRow, error) {
	rows, err := q.db.Query(ctx, idleUnits, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdleUnitsRow
	for rows.Next() {
		var i IdleUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.ResourceName,
			&i.EverRented,
			&i.IdleSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invoiceSummary = `-- name: InvoiceSummary :one
SELECT count(*) FILTER (WHERE i.status IN ('unpaid', 'gateway_pending'))::int AS unpaid_count,
       count(*) FILTER (WHERE i.status = 'overdue')::int AS overdue_count,
       COALESCE(sum((SELECT COALESCE(sum(l.amount), 0) FROM invoice_lines l WHERE l.invoice_id = i.id)), 0)::bigint AS outstanding
  FROM invoices i
 WHERE i.status IN ('unpaid', 'gateway_pending', 'overdue') AND i.deleted_at IS NULL
`

type InvoiceSummaryRow struct {
	UnpaidCount  int32
	OverdueCount int32
	Outstanding  int64
}

// Receivables, not revenue: what is issued and not yet paid.
func (q *Queries) InvoiceSummary(ctx context.Context) (InvoiceSummaryRow, error) {
	row := q.db.QueryRow(ctx, invoiceSummary)
	var i InvoiceSummaryRow
	err := row.Scan(&i.UnpaidCount, &i.OverdueCount, &i.Outstanding)
	return i, err
}

const onboardingState = `-- name: OnboardingState :one
SELECT EXISTS (SELECT 1 FROM resources WHERE deleted_at IS NULL)::boolean AS has_resource,
       EXISTS (SELECT 1 FROM resource_units WHERE deleted_at IS NULL)::boolean AS has_unit,
       EXISTS (SELECT 1 FROM bookings WHERE deleted_at IS NULL)::boolean AS has_booking
`

type OnboardingStateRow struct {
	HasResource bool
	HasUnit     bool
	HasBooking  bool
}

// BR-005: computed from data, never a progress column.
func (q *Queries) OnboardingState(ctx context.Context) (OnboardingStateRow, error) {
	row := q.db.QueryRow(ctx, onboardingState)
	var i OnboardingStateRow
	err := row.Scan(&i.HasResource, &i.HasUnit, &i.HasBooking)
	return i, err
}

const revenuePaidLines = `-- name: RevenuePaidLines :many

SELECT l.kind, COALESCE(sum(l.amount), 0)::bigint AS amount
  FROM invoice_lines l
  JOIN invoices i ON i.id = l.invoice_id
 WHERE i.status = 'paid' AND i.deleted_at IS NULL
   AND i.paid_at >= $1::timestamptz AND i.paid_at < $2::timestamptz
 GROUP BY l.kind
`

type RevenuePaidLinesParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type RevenuePaidLinesRow struct {
	Kind   string
	Amount int64
}

// Laporan dan dashboard.  (S1-056, S1-063)
//
// Every query runs inside InOwnerTx; RLS scopes it to one rental. Ranges are
// written as plain timestamptz comparisons, never tstzrange && -- under RLS
// the range form cannot use an index (000013).
// Cash basis (BR-076): lines of invoices paid inside the period.
func (q *Queries) RevenuePaidLines(ctx context.Context, arg RevenuePaidLinesParams) ([]RevenuePaidLinesRow, error) {
	rows, err := q.db.Query(ctx, revenuePaidLines, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePaidLinesRow
	for rows.Next() {
		var i RevenuePaidLinesRow
		if err := rows.Scan(&i.Kind, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitUtilization = `-- name: UnitUtilization :many
SELECT u.id, u.code, u.label, r.name AS resource_name,
       COALESCE(sum(EXTRACT(EPOCH FROM
         LEAST(COALESCE(b.actual_return_at, b.end_at), $1::timestamptz)
         - GREATEST(b.start_at, $2::timestamptz)))
         -- FILTER: LEAST/GREATEST skip NULLs, so a unit with no booking would
         -- otherwise count as rented for the whole period.
         FILTER (WHERE b.id IS NOT NULL), 0)::float8 AS rented_seconds
  FROM resource_units u
  JOIN resources r ON r.id = u.resource_id AND r.deleted_at IS NULL
  LEFT JOIN bookings b ON b.resource_unit_id = u.id AND b.deleted_at IS NULL
        AND b.status IN ('picked_up', 'returned', 'completed')
        AND b.start_at < $1::timestamptz
        AND COALESCE(b.actual_return_at, b.end_at) > $2::timestamptz
 WHERE u.status = 'active' AND u.deleted_at IS NULL
 GROUP BY u.id, u.code, u.label, r.name
 ORDER BY rented_seconds, u.code
`

type UnitUtilizationParams struct {
	ToAt   time.Time
	FromAt time.Time
}

type UnitUtilizationRow struct {
	ID            uuid.UUID
	Code          string
	Label         *string
	ResourceName  string
	RentedSeconds float64
}

// Seconds of each active unit covered by a booking that actually went out.
func (q *Queries) UnitUtilization(ctx context.Context, arg UnitUtilizationParams) ([]UnitUtilizationRow, error) {
	rows, err := q.db.Query(ctx, unitUtilization, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitUtilizationRow
	for rows.Next() {
		var i UnitUtilizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.ResourceName,
			&i.RentedSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
