// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getOwnerProfile = `-- name: GetOwnerProfile :one
SELECT name, slug, whatsapp, address, operating_hours,
       bank_name, bank_account_number, bank_account_holder
  FROM owners
 WHERE id = $1
`

type GetOwnerProfileRow struct {
	Name              string
	Slug              *string
	Whatsapp          *string
	Address           *string
	OperatingHours    *string
	BankName          *string
	BankAccountNumber *string
	BankAccountHolder *string
}

// What renters see of the business: the public page (BR-096) and the portal's
// "cara bayar" (S1-062). owners has no RLS; the id comes from the Host lookup.
func (q *Queries) GetOwnerProfile(ctx context.Context, id uuid.UUID) (GetOwnerProfileRow, error) {
	row := q.db.QueryRow(ctx, getOwnerProfile, id)
	var i GetOwnerProfileRow
	err := row.Scan(
		&i.Name,
		&i.Slug,
		&i.Whatsapp,
		&i.Address,
		&i.OperatingHours,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountHolder,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT slug, booking_code_prefix, require_payment_before_pickup,
       draft_expiry_hours, payment_due_hours, no_show_tolerance_hours,
       notify_pickup_reminder, notify_return_reminder, notify_overdue_reminder,
       whatsapp, address, operating_hours,
       bank_name, bank_account_number, bank_account_holder, allowed_origins
  FROM owners
 WHERE id = $1
`

type GetSettingsRow struct {
	Slug                       *string
	BookingCodePrefix          string
	RequirePaymentBeforePickup bool
	DraftExpiryHours           int32
	PaymentDueHours            int32
	NoShowToleranceHours       int32
	NotifyPickupReminder       bool
	NotifyReturnReminder       bool
	NotifyOverdueReminder      bool
	Whatsapp                   *string
	Address                    *string
	OperatingHours             *string
	BankName                   *string
	BankAccountNumber          *string
	BankAccountHolder          *string
	AllowedOrigins             []string
}

// Runs inside InOwnerTx like everything else, but owners has no RLS (it IS the
// tenant), so the WHERE clause is what scopes it -- and the id comes from the
// owner context, never from the request.
func (q *Queries) GetSettings(ctx context.Context, id uuid.UUID) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings, id)
	var i GetSettingsRow
	err := row.Scan(
		&i.Slug,
		&i.BookingCodePrefix,
		&i.RequirePaymentBeforePickup,
		&i.DraftExpiryHours,
		&i.PaymentDueHours,
		&i.NoShowToleranceHours,
		&i.NotifyPickupReminder,
		&i.NotifyReturnReminder,
		&i.NotifyOverdueReminder,
		&i.Whatsapp,
		&i.Address,
		&i.OperatingHours,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountHolder,
		&i.AllowedOrigins,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE owners SET
    slug                          = COALESCE($1,                          slug),
    booking_code_prefix           = COALESCE($2,           booking_code_prefix),
    require_payment_before_pickup = COALESCE($3, require_payment_before_pickup),
    draft_expiry_hours            = COALESCE($4,            draft_expiry_hours),
    payment_due_hours             = COALESCE($5,             payment_due_hours),
    no_show_tolerance_hours       = COALESCE($6,       no_show_tolerance_hours),
    notify_pickup_reminder        = COALESCE($7,        notify_pickup_reminder),
    notify_return_reminder        = COALESCE($8,        notify_return_reminder),
    notify_overdue_reminder       = COALESCE($9,       notify_overdue_reminder),
    whatsapp                      = COALESCE($10,                      whatsapp),
    address                       = COALESCE($11,                       address),
    operating_hours               = COALESCE($12,               operating_hours),
    bank_name                     = COALESCE($13,                     bank_name),
    bank_account_number           = COALESCE($14,           bank_account_number),
    bank_account_holder           = COALESCE($15,           bank_account_holder),
    allowed_origins               = COALESCE($16::text[],       allowed_origins),
    updated_at                    = now()
 WHERE id = $17
RETURNING slug, booking_code_prefix, require_payment_before_pickup,
          draft_expiry_hours, payment_due_hours, no_show_tolerance_hours,
          notify_pickup_reminder, notify_return_reminder, notify_overdue_reminder,
          whatsapp, address, operating_hours,
          bank_name, bank_account_number, bank_account_holder, allowed_origins
`

type UpdateSettingsParams struct {
	Slug                       *string
	BookingCodePrefix          *string
	RequirePaymentBeforePickup *bool
	DraftExpiryHours           *int32
	PaymentDueHours            *int32
	NoShowToleranceHours       *int32
	NotifyPickupReminder       *bool
	NotifyReturnReminder       *bool
	NotifyOverdueReminder      *bool
	Whatsapp                   *string
	Address                    *string
	OperatingHours             *string
	BankName                   *string
	BankAccountNumber          *string
	BankAccountHolder          *string
	AllowedOrigins             []string
	ID                         uuid.UUID
}

type UpdateSettingsRow struct {
	Slug                       *string
	BookingCodePrefix          string
	RequirePaymentBeforePickup bool
	DraftExpiryHours           int32
	PaymentDueHours            int32
	NoShowToleranceHours       int32
	NotifyPickupReminder       bool
	NotifyReturnReminder       bool
	NotifyOverdueReminder      bool
	Whatsapp                   *string
	Address                    *string
	OperatingHours             *string
	BankName                   *string
	BankAccountNumber          *string
	BankAccountHolder          *string
	AllowedOrigins             []string
}

// COALESCE per column: a NULL argument means "the client omitted this key", so
// the current value stands. That is what keeps PATCH from being a disguised PUT
// that blanks every knob the caller did not happen to mention.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (UpdateSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.Slug,
		arg.BookingCodePrefix,
		arg.RequirePaymentBeforePickup,
		arg.DraftExpiryHours,
		arg.PaymentDueHours,
		arg.NoShowToleranceHours,
		arg.NotifyPickupReminder,
		arg.NotifyReturnReminder,
		arg.NotifyOverdueReminder,
		arg.Whatsapp,
		arg.Address,
		arg.OperatingHours,
		arg.BankName,
		arg.BankAccountNumber,
		arg.BankAccountHolder,
		arg.AllowedOrigins,
		arg.ID,
	)
	var i UpdateSettingsRow
	err := row.Scan(
		&i.Slug,
		&i.BookingCodePrefix,
		&i.RequirePaymentBeforePickup,
		&i.DraftExpiryHours,
		&i.PaymentDueHours,
		&i.NoShowToleranceHours,
		&i.NotifyPickupReminder,
		&i.NotifyReturnReminder,
		&i.NotifyOverdueReminder,
		&i.Whatsapp,
		&i.Address,
		&i.OperatingHours,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountHolder,
		&i.AllowedOrigins,
	)
	return i, err
}
