// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const disableUser = `-- name: DisableUser :execrows
UPDATE users SET status = 'disabled', updated_at = now()
 WHERE id = $1 AND status <> 'disabled'
`

// Not a DELETE, and there is no query in this file that is. created_by columns
// elsewhere have to stay explicable, so the row outlives the account.
func (q *Queries) DisableUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, disableUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inviteUser = `-- name: InviteUser :one
INSERT INTO users (id, owner_id, email, name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, role, status, last_login_at
`

type InviteUserParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Email   string
	Name    string
	Role    string
}

type InviteUserRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	Role        string
	Status      string
	LastLoginAt *time.Time
}

// No password_hash: the row exists so the invitee has something to accept.
// status defaults to 'invited' in the schema and is not settable from here.
func (q *Queries) InviteUser(ctx context.Context, arg InviteUserParams) (InviteUserRow, error) {
	row := q.db.QueryRow(ctx, inviteUser,
		arg.ID,
		arg.OwnerID,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i InviteUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many

SELECT id, email, name, role, status, last_login_at
  FROM users
 ORDER BY created_at
`

type ListUsersRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	Role        string
	Status      string
	LastLoginAt *time.Time
}

// Every query here runs inside InOwnerTx, so RLS has already scoped `users` to
// one rental. That is what makes the id-taking queries return zero rows for
// another owner's id -- no ownership check in Go, and none wanted (BR-001).
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveOwners = `-- name: LockActiveOwners :many
SELECT id FROM users WHERE role = 'owner' AND status = 'active' FOR UPDATE
`

// FOR UPDATE so two owners demoting each other at once queue up: the second
// re-reads after the first commits and sees one owner left (S1-067).
func (q *Queries) LockActiveOwners(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockActiveOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    role       = COALESCE($1,   role),
    status     = COALESCE($2, status),
    updated_at = now()
 WHERE id = $3
RETURNING id, email, name, role, status, last_login_at
`

type UpdateUserParams struct {
	Role   *string
	Status *string
	ID     uuid.UUID
}

type UpdateUserRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	Role        string
	Status      string
	LastLoginAt *time.Time
}

// COALESCE for the same reason as UpdateSettings: absent key, value stands.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Role, arg.Status, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1)
`

// Distinguishes "already disabled" (204, idempotent) from "not in this rental"
// (404). DisableUser alone cannot: both return zero rows.
func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
